// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: public/portal/v1/portal.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetSubscriptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscriptionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscriptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubscriptionRequestMultiError, or nil if none found.
func (m *GetSubscriptionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscriptionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CategoryId

	if m.Language != nil {
		// no validation rules for Language
	}

	if len(errors) > 0 {
		return GetSubscriptionRequestMultiError(errors)
	}

	return nil
}

// GetSubscriptionRequestMultiError is an error wrapping multiple validation
// errors returned by GetSubscriptionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSubscriptionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscriptionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscriptionRequestMultiError) AllErrors() []error { return m }

// GetSubscriptionRequestValidationError is the validation error returned by
// GetSubscriptionRequest.Validate if the designated constraints aren't met.
type GetSubscriptionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscriptionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscriptionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscriptionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscriptionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscriptionRequestValidationError) ErrorName() string {
	return "GetSubscriptionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscriptionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscriptionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscriptionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscriptionRequestValidationError{}

// Validate checks the field values on GetSubscriptionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscriptionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscriptionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubscriptionReplyMultiError, or nil if none found.
func (m *GetSubscriptionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscriptionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetSubscriptionReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetSubscriptionReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetSubscriptionReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetSubscriptionReplyMultiError(errors)
	}

	return nil
}

// GetSubscriptionReplyMultiError is an error wrapping multiple validation
// errors returned by GetSubscriptionReply.ValidateAll() if the designated
// constraints aren't met.
type GetSubscriptionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscriptionReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscriptionReplyMultiError) AllErrors() []error { return m }

// GetSubscriptionReplyValidationError is the validation error returned by
// GetSubscriptionReply.Validate if the designated constraints aren't met.
type GetSubscriptionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscriptionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscriptionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscriptionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscriptionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscriptionReplyValidationError) ErrorName() string {
	return "GetSubscriptionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscriptionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscriptionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscriptionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscriptionReplyValidationError{}

// Validate checks the field values on SubscribeInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SubscribeInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscribeInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SubscribeInfoMultiError, or
// nil if none found.
func (m *SubscribeInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscribeInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Language

	// no validation rules for Description

	// no validation rules for UnitPrice

	// no validation rules for UnitTime

	for idx, item := range m.GetDiscount() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SubscribeInfoValidationError{
						field:  fmt.Sprintf("Discount[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SubscribeInfoValidationError{
						field:  fmt.Sprintf("Discount[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SubscribeInfoValidationError{
					field:  fmt.Sprintf("Discount[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Replacement

	// no validation rules for Inventory

	// no validation rules for Traffic

	// no validation rules for SpeedLimit

	// no validation rules for DeviceLimit

	// no validation rules for Quota

	// no validation rules for CategoryId

	// no validation rules for CategoryName

	// no validation rules for NodeGroupId

	for idx, item := range m.GetTrafficLimit() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SubscribeInfoValidationError{
						field:  fmt.Sprintf("TrafficLimit[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SubscribeInfoValidationError{
						field:  fmt.Sprintf("TrafficLimit[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SubscribeInfoValidationError{
					field:  fmt.Sprintf("TrafficLimit[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Show

	// no validation rules for Sell

	// no validation rules for Sort

	// no validation rules for DeductionRatio

	// no validation rules for AllowDeduction

	// no validation rules for ResetCycle

	// no validation rules for RenewalReset

	// no validation rules for ShowOriginalPrice

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	for idx, item := range m.GetPriceOptions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SubscribeInfoValidationError{
						field:  fmt.Sprintf("PriceOptions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SubscribeInfoValidationError{
						field:  fmt.Sprintf("PriceOptions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SubscribeInfoValidationError{
					field:  fmt.Sprintf("PriceOptions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SubscribeInfoMultiError(errors)
	}

	return nil
}

// SubscribeInfoMultiError is an error wrapping multiple validation errors
// returned by SubscribeInfo.ValidateAll() if the designated constraints
// aren't met.
type SubscribeInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscribeInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscribeInfoMultiError) AllErrors() []error { return m }

// SubscribeInfoValidationError is the validation error returned by
// SubscribeInfo.Validate if the designated constraints aren't met.
type SubscribeInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscribeInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscribeInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscribeInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscribeInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscribeInfoValidationError) ErrorName() string { return "SubscribeInfoValidationError" }

// Error satisfies the builtin error interface
func (e SubscribeInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscribeInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscribeInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscribeInfoValidationError{}

// Validate checks the field values on SubscribePriceOption with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubscribePriceOption) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscribePriceOption with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubscribePriceOptionMultiError, or nil if none found.
func (m *SubscribePriceOption) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscribePriceOption) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SubscribeId

	// no validation rules for Name

	// no validation rules for DurationUnit

	// no validation rules for DurationValue

	// no validation rules for Price

	// no validation rules for OriginalPrice

	// no validation rules for Inventory

	// no validation rules for Show

	// no validation rules for Sell

	// no validation rules for IsDefault

	// no validation rules for Sort

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return SubscribePriceOptionMultiError(errors)
	}

	return nil
}

// SubscribePriceOptionMultiError is an error wrapping multiple validation
// errors returned by SubscribePriceOption.ValidateAll() if the designated
// constraints aren't met.
type SubscribePriceOptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscribePriceOptionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscribePriceOptionMultiError) AllErrors() []error { return m }

// SubscribePriceOptionValidationError is the validation error returned by
// SubscribePriceOption.Validate if the designated constraints aren't met.
type SubscribePriceOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscribePriceOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscribePriceOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscribePriceOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscribePriceOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscribePriceOptionValidationError) ErrorName() string {
	return "SubscribePriceOptionValidationError"
}

// Error satisfies the builtin error interface
func (e SubscribePriceOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscribePriceOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscribePriceOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscribePriceOptionValidationError{}

// Validate checks the field values on SubscribeCategory with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SubscribeCategory) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscribeCategory with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubscribeCategoryMultiError, or nil if none found.
func (m *SubscribeCategory) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscribeCategory) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ParentId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Language

	// no validation rules for Show

	// no validation rules for Sort

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SubscribeCategoryValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SubscribeCategoryValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SubscribeCategoryValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SubscribeCategoryValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SubscribeCategoryValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SubscribeCategoryValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SubscribeCategoryMultiError(errors)
	}

	return nil
}

// SubscribeCategoryMultiError is an error wrapping multiple validation errors
// returned by SubscribeCategory.ValidateAll() if the designated constraints
// aren't met.
type SubscribeCategoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscribeCategoryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscribeCategoryMultiError) AllErrors() []error { return m }

// SubscribeCategoryValidationError is the validation error returned by
// SubscribeCategory.Validate if the designated constraints aren't met.
type SubscribeCategoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscribeCategoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscribeCategoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscribeCategoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscribeCategoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscribeCategoryValidationError) ErrorName() string {
	return "SubscribeCategoryValidationError"
}

// Error satisfies the builtin error interface
func (e SubscribeCategoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscribeCategory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscribeCategoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscribeCategoryValidationError{}

// Validate checks the field values on GetSubscriptionCatalogRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscriptionCatalogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscriptionCatalogRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetSubscriptionCatalogRequestMultiError, or nil if none found.
func (m *GetSubscriptionCatalogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscriptionCatalogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Language != nil {
		// no validation rules for Language
	}

	if len(errors) > 0 {
		return GetSubscriptionCatalogRequestMultiError(errors)
	}

	return nil
}

// GetSubscriptionCatalogRequestMultiError is an error wrapping multiple
// validation errors returned by GetSubscriptionCatalogRequest.ValidateAll()
// if the designated constraints aren't met.
type GetSubscriptionCatalogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscriptionCatalogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscriptionCatalogRequestMultiError) AllErrors() []error { return m }

// GetSubscriptionCatalogRequestValidationError is the validation error
// returned by GetSubscriptionCatalogRequest.Validate if the designated
// constraints aren't met.
type GetSubscriptionCatalogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscriptionCatalogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscriptionCatalogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscriptionCatalogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscriptionCatalogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscriptionCatalogRequestValidationError) ErrorName() string {
	return "GetSubscriptionCatalogRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscriptionCatalogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscriptionCatalogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscriptionCatalogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscriptionCatalogRequestValidationError{}

// Validate checks the field values on GetSubscriptionCatalogReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscriptionCatalogReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscriptionCatalogReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubscriptionCatalogReplyMultiError, or nil if none found.
func (m *GetSubscriptionCatalogReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscriptionCatalogReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetCategories() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetSubscriptionCatalogReplyValidationError{
						field:  fmt.Sprintf("Categories[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetSubscriptionCatalogReplyValidationError{
						field:  fmt.Sprintf("Categories[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetSubscriptionCatalogReplyValidationError{
					field:  fmt.Sprintf("Categories[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetUncategorized() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetSubscriptionCatalogReplyValidationError{
						field:  fmt.Sprintf("Uncategorized[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetSubscriptionCatalogReplyValidationError{
						field:  fmt.Sprintf("Uncategorized[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetSubscriptionCatalogReplyValidationError{
					field:  fmt.Sprintf("Uncategorized[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return GetSubscriptionCatalogReplyMultiError(errors)
	}

	return nil
}

// GetSubscriptionCatalogReplyMultiError is an error wrapping multiple
// validation errors returned by GetSubscriptionCatalogReply.ValidateAll() if
// the designated constraints aren't met.
type GetSubscriptionCatalogReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscriptionCatalogReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscriptionCatalogReplyMultiError) AllErrors() []error { return m }

// GetSubscriptionCatalogReplyValidationError is the validation error returned
// by GetSubscriptionCatalogReply.Validate if the designated constraints
// aren't met.
type GetSubscriptionCatalogReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscriptionCatalogReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscriptionCatalogReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscriptionCatalogReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscriptionCatalogReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscriptionCatalogReplyValidationError) ErrorName() string {
	return "GetSubscriptionCatalogReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscriptionCatalogReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscriptionCatalogReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscriptionCatalogReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscriptionCatalogReplyValidationError{}

// Validate checks the field values on SubscribeDiscount with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SubscribeDiscount) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscribeDiscount with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubscribeDiscountMultiError, or nil if none found.
func (m *SubscribeDiscount) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscribeDiscount) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Quantity

	// no validation rules for Discount

	if len(errors) > 0 {
		return SubscribeDiscountMultiError(errors)
	}

	return nil
}

// SubscribeDiscountMultiError is an error wrapping multiple validation errors
// returned by SubscribeDiscount.ValidateAll() if the designated constraints
// aren't met.
type SubscribeDiscountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscribeDiscountMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscribeDiscountMultiError) AllErrors() []error { return m }

// SubscribeDiscountValidationError is the validation error returned by
// SubscribeDiscount.Validate if the designated constraints aren't met.
type SubscribeDiscountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscribeDiscountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscribeDiscountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscribeDiscountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscribeDiscountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscribeDiscountValidationError) ErrorName() string {
	return "SubscribeDiscountValidationError"
}

// Error satisfies the builtin error interface
func (e SubscribeDiscountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscribeDiscount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscribeDiscountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscribeDiscountValidationError{}

// Validate checks the field values on TrafficLimit with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TrafficLimit) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrafficLimit with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TrafficLimitMultiError, or
// nil if none found.
func (m *TrafficLimit) ValidateAll() error {
	return m.validate(true)
}

func (m *TrafficLimit) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StatType

	// no validation rules for StatValue

	// no validation rules for TrafficUsage

	// no validation rules for SpeedLimit

	if len(errors) > 0 {
		return TrafficLimitMultiError(errors)
	}

	return nil
}

// TrafficLimitMultiError is an error wrapping multiple validation errors
// returned by TrafficLimit.ValidateAll() if the designated constraints aren't met.
type TrafficLimitMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrafficLimitMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrafficLimitMultiError) AllErrors() []error { return m }

// TrafficLimitValidationError is the validation error returned by
// TrafficLimit.Validate if the designated constraints aren't met.
type TrafficLimitValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrafficLimitValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrafficLimitValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrafficLimitValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrafficLimitValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrafficLimitValidationError) ErrorName() string { return "TrafficLimitValidationError" }

// Error satisfies the builtin error interface
func (e TrafficLimitValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrafficLimit.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrafficLimitValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrafficLimitValidationError{}

// Validate checks the field values on PrePurchaseOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PrePurchaseOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PrePurchaseOrderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PrePurchaseOrderRequestMultiError, or nil if none found.
func (m *PrePurchaseOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PrePurchaseOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Payment

	// no validation rules for SubscribeId

	// no validation rules for Quantity

	// no validation rules for PriceOptionId

	if m.Coupon != nil {
		// no validation rules for Coupon
	}

	if len(errors) > 0 {
		return PrePurchaseOrderRequestMultiError(errors)
	}

	return nil
}

// PrePurchaseOrderRequestMultiError is an error wrapping multiple validation
// errors returned by PrePurchaseOrderRequest.ValidateAll() if the designated
// constraints aren't met.
type PrePurchaseOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PrePurchaseOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PrePurchaseOrderRequestMultiError) AllErrors() []error { return m }

// PrePurchaseOrderRequestValidationError is the validation error returned by
// PrePurchaseOrderRequest.Validate if the designated constraints aren't met.
type PrePurchaseOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrePurchaseOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrePurchaseOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrePurchaseOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrePurchaseOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrePurchaseOrderRequestValidationError) ErrorName() string {
	return "PrePurchaseOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PrePurchaseOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrePurchaseOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrePurchaseOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrePurchaseOrderRequestValidationError{}

// Validate checks the field values on PrePurchaseOrderReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PrePurchaseOrderReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PrePurchaseOrderReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PrePurchaseOrderReplyMultiError, or nil if none found.
func (m *PrePurchaseOrderReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PrePurchaseOrderReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Price

	// no validation rules for Amount

	// no validation rules for Discount

	// no validation rules for Coupon

	// no validation rules for CouponDiscount

	// no validation rules for FeeAmount

	if len(errors) > 0 {
		return PrePurchaseOrderReplyMultiError(errors)
	}

	return nil
}

// PrePurchaseOrderReplyMultiError is an error wrapping multiple validation
// errors returned by PrePurchaseOrderReply.ValidateAll() if the designated
// constraints aren't met.
type PrePurchaseOrderReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PrePurchaseOrderReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PrePurchaseOrderReplyMultiError) AllErrors() []error { return m }

// PrePurchaseOrderReplyValidationError is the validation error returned by
// PrePurchaseOrderReply.Validate if the designated constraints aren't met.
type PrePurchaseOrderReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrePurchaseOrderReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrePurchaseOrderReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrePurchaseOrderReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrePurchaseOrderReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrePurchaseOrderReplyValidationError) ErrorName() string {
	return "PrePurchaseOrderReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PrePurchaseOrderReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrePurchaseOrderReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrePurchaseOrderReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrePurchaseOrderReplyValidationError{}

// Validate checks the field values on PurchaseRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PurchaseRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PurchaseRequestMultiError, or nil if none found.
func (m *PurchaseRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AuthType

	// no validation rules for Identifier

	// no validation rules for Password

	// no validation rules for Payment

	// no validation rules for SubscribeId

	// no validation rules for Quantity

	// no validation rules for PriceOptionId

	if m.Coupon != nil {
		// no validation rules for Coupon
	}

	if m.InviteCode != nil {
		// no validation rules for InviteCode
	}

	if m.TurnstileToken != nil {
		// no validation rules for TurnstileToken
	}

	if len(errors) > 0 {
		return PurchaseRequestMultiError(errors)
	}

	return nil
}

// PurchaseRequestMultiError is an error wrapping multiple validation errors
// returned by PurchaseRequest.ValidateAll() if the designated constraints
// aren't met.
type PurchaseRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseRequestMultiError) AllErrors() []error { return m }

// PurchaseRequestValidationError is the validation error returned by
// PurchaseRequest.Validate if the designated constraints aren't met.
type PurchaseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseRequestValidationError) ErrorName() string { return "PurchaseRequestValidationError" }

// Error satisfies the builtin error interface
func (e PurchaseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseRequestValidationError{}

// Validate checks the field values on PurchaseReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PurchaseReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PurchaseReplyMultiError, or
// nil if none found.
func (m *PurchaseReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	if len(errors) > 0 {
		return PurchaseReplyMultiError(errors)
	}

	return nil
}

// PurchaseReplyMultiError is an error wrapping multiple validation errors
// returned by PurchaseReply.ValidateAll() if the designated constraints
// aren't met.
type PurchaseReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseReplyMultiError) AllErrors() []error { return m }

// PurchaseReplyValidationError is the validation error returned by
// PurchaseReply.Validate if the designated constraints aren't met.
type PurchaseReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseReplyValidationError) ErrorName() string { return "PurchaseReplyValidationError" }

// Error satisfies the builtin error interface
func (e PurchaseReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseReplyValidationError{}

// Validate checks the field values on GetAvailablePaymentMethodsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAvailablePaymentMethodsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAvailablePaymentMethodsReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetAvailablePaymentMethodsReplyMultiError, or nil if none found.
func (m *GetAvailablePaymentMethodsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAvailablePaymentMethodsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMethods() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAvailablePaymentMethodsReplyValidationError{
						field:  fmt.Sprintf("Methods[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAvailablePaymentMethodsReplyValidationError{
						field:  fmt.Sprintf("Methods[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAvailablePaymentMethodsReplyValidationError{
					field:  fmt.Sprintf("Methods[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAvailablePaymentMethodsReplyMultiError(errors)
	}

	return nil
}

// GetAvailablePaymentMethodsReplyMultiError is an error wrapping multiple
// validation errors returned by GetAvailablePaymentMethodsReply.ValidateAll()
// if the designated constraints aren't met.
type GetAvailablePaymentMethodsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAvailablePaymentMethodsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAvailablePaymentMethodsReplyMultiError) AllErrors() []error { return m }

// GetAvailablePaymentMethodsReplyValidationError is the validation error
// returned by GetAvailablePaymentMethodsReply.Validate if the designated
// constraints aren't met.
type GetAvailablePaymentMethodsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAvailablePaymentMethodsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAvailablePaymentMethodsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAvailablePaymentMethodsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAvailablePaymentMethodsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAvailablePaymentMethodsReplyValidationError) ErrorName() string {
	return "GetAvailablePaymentMethodsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetAvailablePaymentMethodsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAvailablePaymentMethodsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAvailablePaymentMethodsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAvailablePaymentMethodsReplyValidationError{}

// Validate checks the field values on PaymentMethod with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PaymentMethod) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentMethod with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaymentMethodMultiError, or
// nil if none found.
func (m *PaymentMethod) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentMethod) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Platform

	// no validation rules for Description

	// no validation rules for Icon

	// no validation rules for FeeMode

	// no validation rules for FeePercent

	// no validation rules for FeeAmount

	if len(errors) > 0 {
		return PaymentMethodMultiError(errors)
	}

	return nil
}

// PaymentMethodMultiError is an error wrapping multiple validation errors
// returned by PaymentMethod.ValidateAll() if the designated constraints
// aren't met.
type PaymentMethodMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentMethodMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentMethodMultiError) AllErrors() []error { return m }

// PaymentMethodValidationError is the validation error returned by
// PaymentMethod.Validate if the designated constraints aren't met.
type PaymentMethodValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentMethodValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentMethodValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentMethodValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentMethodValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentMethodValidationError) ErrorName() string { return "PaymentMethodValidationError" }

// Error satisfies the builtin error interface
func (e PaymentMethodValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentMethod.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentMethodValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentMethodValidationError{}

// Validate checks the field values on PurchaseCheckoutRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PurchaseCheckoutRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseCheckoutRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PurchaseCheckoutRequestMultiError, or nil if none found.
func (m *PurchaseCheckoutRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseCheckoutRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	if m.ReturnUrl != nil {
		// no validation rules for ReturnUrl
	}

	if len(errors) > 0 {
		return PurchaseCheckoutRequestMultiError(errors)
	}

	return nil
}

// PurchaseCheckoutRequestMultiError is an error wrapping multiple validation
// errors returned by PurchaseCheckoutRequest.ValidateAll() if the designated
// constraints aren't met.
type PurchaseCheckoutRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseCheckoutRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseCheckoutRequestMultiError) AllErrors() []error { return m }

// PurchaseCheckoutRequestValidationError is the validation error returned by
// PurchaseCheckoutRequest.Validate if the designated constraints aren't met.
type PurchaseCheckoutRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseCheckoutRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseCheckoutRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseCheckoutRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseCheckoutRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseCheckoutRequestValidationError) ErrorName() string {
	return "PurchaseCheckoutRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PurchaseCheckoutRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseCheckoutRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseCheckoutRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseCheckoutRequestValidationError{}

// Validate checks the field values on PurchaseCheckoutReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PurchaseCheckoutReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseCheckoutReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PurchaseCheckoutReplyMultiError, or nil if none found.
func (m *PurchaseCheckoutReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseCheckoutReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if m.CheckoutUrl != nil {
		// no validation rules for CheckoutUrl
	}

	if m.Stripe != nil {

		if all {
			switch v := interface{}(m.GetStripe()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PurchaseCheckoutReplyValidationError{
						field:  "Stripe",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PurchaseCheckoutReplyValidationError{
						field:  "Stripe",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStripe()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PurchaseCheckoutReplyValidationError{
					field:  "Stripe",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PurchaseCheckoutReplyMultiError(errors)
	}

	return nil
}

// PurchaseCheckoutReplyMultiError is an error wrapping multiple validation
// errors returned by PurchaseCheckoutReply.ValidateAll() if the designated
// constraints aren't met.
type PurchaseCheckoutReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseCheckoutReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseCheckoutReplyMultiError) AllErrors() []error { return m }

// PurchaseCheckoutReplyValidationError is the validation error returned by
// PurchaseCheckoutReply.Validate if the designated constraints aren't met.
type PurchaseCheckoutReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseCheckoutReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseCheckoutReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseCheckoutReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseCheckoutReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseCheckoutReplyValidationError) ErrorName() string {
	return "PurchaseCheckoutReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PurchaseCheckoutReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseCheckoutReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseCheckoutReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseCheckoutReplyValidationError{}

// Validate checks the field values on StripePayment with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StripePayment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StripePayment with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StripePaymentMultiError, or
// nil if none found.
func (m *StripePayment) ValidateAll() error {
	return m.validate(true)
}

func (m *StripePayment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PublishableKey

	// no validation rules for ClientSecret

	// no validation rules for Method

	if len(errors) > 0 {
		return StripePaymentMultiError(errors)
	}

	return nil
}

// StripePaymentMultiError is an error wrapping multiple validation errors
// returned by StripePayment.ValidateAll() if the designated constraints
// aren't met.
type StripePaymentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StripePaymentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StripePaymentMultiError) AllErrors() []error { return m }

// StripePaymentValidationError is the validation error returned by
// StripePayment.Validate if the designated constraints aren't met.
type StripePaymentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StripePaymentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StripePaymentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StripePaymentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StripePaymentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StripePaymentValidationError) ErrorName() string { return "StripePaymentValidationError" }

// Error satisfies the builtin error interface
func (e StripePaymentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStripePayment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StripePaymentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StripePaymentValidationError{}

// Validate checks the field values on QueryPurchaseOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryPurchaseOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryPurchaseOrderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryPurchaseOrderRequestMultiError, or nil if none found.
func (m *QueryPurchaseOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryPurchaseOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AuthType

	// no validation rules for Identifier

	// no validation rules for OrderNo

	if len(errors) > 0 {
		return QueryPurchaseOrderRequestMultiError(errors)
	}

	return nil
}

// QueryPurchaseOrderRequestMultiError is an error wrapping multiple validation
// errors returned by QueryPurchaseOrderRequest.ValidateAll() if the
// designated constraints aren't met.
type QueryPurchaseOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryPurchaseOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryPurchaseOrderRequestMultiError) AllErrors() []error { return m }

// QueryPurchaseOrderRequestValidationError is the validation error returned by
// QueryPurchaseOrderRequest.Validate if the designated constraints aren't met.
type QueryPurchaseOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryPurchaseOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryPurchaseOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryPurchaseOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryPurchaseOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryPurchaseOrderRequestValidationError) ErrorName() string {
	return "QueryPurchaseOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryPurchaseOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryPurchaseOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryPurchaseOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryPurchaseOrderRequestValidationError{}

// Validate checks the field values on QueryPurchaseOrderReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryPurchaseOrderReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryPurchaseOrderReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryPurchaseOrderReplyMultiError, or nil if none found.
func (m *QueryPurchaseOrderReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryPurchaseOrderReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	if all {
		switch v := interface{}(m.GetSubscribe()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryPurchaseOrderReplyValidationError{
					field:  "Subscribe",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryPurchaseOrderReplyValidationError{
					field:  "Subscribe",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSubscribe()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryPurchaseOrderReplyValidationError{
				field:  "Subscribe",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Quantity

	// no validation rules for Price

	// no validation rules for Amount

	// no validation rules for Discount

	// no validation rules for Coupon

	// no validation rules for CouponDiscount

	// no validation rules for FeeAmount

	if all {
		switch v := interface{}(m.GetPayment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryPurchaseOrderReplyValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryPurchaseOrderReplyValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPayment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryPurchaseOrderReplyValidationError{
				field:  "Payment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for Token

	// no validation rules for PriceOptionId

	// no validation rules for PriceOptionName

	// no validation rules for DurationUnit

	// no validation rules for DurationValue

	// no validation rules for OptionPrice

	if len(errors) > 0 {
		return QueryPurchaseOrderReplyMultiError(errors)
	}

	return nil
}

// QueryPurchaseOrderReplyMultiError is an error wrapping multiple validation
// errors returned by QueryPurchaseOrderReply.ValidateAll() if the designated
// constraints aren't met.
type QueryPurchaseOrderReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryPurchaseOrderReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryPurchaseOrderReplyMultiError) AllErrors() []error { return m }

// QueryPurchaseOrderReplyValidationError is the validation error returned by
// QueryPurchaseOrderReply.Validate if the designated constraints aren't met.
type QueryPurchaseOrderReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryPurchaseOrderReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryPurchaseOrderReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryPurchaseOrderReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryPurchaseOrderReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryPurchaseOrderReplyValidationError) ErrorName() string {
	return "QueryPurchaseOrderReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryPurchaseOrderReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryPurchaseOrderReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryPurchaseOrderReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryPurchaseOrderReplyValidationError{}
