// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: public/order/v1/order.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CloseOrderRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CloseOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CloseOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CloseOrderRequestMultiError, or nil if none found.
func (m *CloseOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CloseOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	if len(errors) > 0 {
		return CloseOrderRequestMultiError(errors)
	}

	return nil
}

// CloseOrderRequestMultiError is an error wrapping multiple validation errors
// returned by CloseOrderRequest.ValidateAll() if the designated constraints
// aren't met.
type CloseOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CloseOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CloseOrderRequestMultiError) AllErrors() []error { return m }

// CloseOrderRequestValidationError is the validation error returned by
// CloseOrderRequest.Validate if the designated constraints aren't met.
type CloseOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CloseOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CloseOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CloseOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CloseOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CloseOrderRequestValidationError) ErrorName() string {
	return "CloseOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CloseOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCloseOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CloseOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CloseOrderRequestValidationError{}

// Validate checks the field values on QueryOrderDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryOrderDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryOrderDetailRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryOrderDetailRequestMultiError, or nil if none found.
func (m *QueryOrderDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryOrderDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	if len(errors) > 0 {
		return QueryOrderDetailRequestMultiError(errors)
	}

	return nil
}

// QueryOrderDetailRequestMultiError is an error wrapping multiple validation
// errors returned by QueryOrderDetailRequest.ValidateAll() if the designated
// constraints aren't met.
type QueryOrderDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryOrderDetailRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryOrderDetailRequestMultiError) AllErrors() []error { return m }

// QueryOrderDetailRequestValidationError is the validation error returned by
// QueryOrderDetailRequest.Validate if the designated constraints aren't met.
type QueryOrderDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryOrderDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryOrderDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryOrderDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryOrderDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryOrderDetailRequestValidationError) ErrorName() string {
	return "QueryOrderDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryOrderDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryOrderDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryOrderDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryOrderDetailRequestValidationError{}

// Validate checks the field values on QueryOrderListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryOrderListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryOrderListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryOrderListRequestMultiError, or nil if none found.
func (m *QueryOrderListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryOrderListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Size

	if len(errors) > 0 {
		return QueryOrderListRequestMultiError(errors)
	}

	return nil
}

// QueryOrderListRequestMultiError is an error wrapping multiple validation
// errors returned by QueryOrderListRequest.ValidateAll() if the designated
// constraints aren't met.
type QueryOrderListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryOrderListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryOrderListRequestMultiError) AllErrors() []error { return m }

// QueryOrderListRequestValidationError is the validation error returned by
// QueryOrderListRequest.Validate if the designated constraints aren't met.
type QueryOrderListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryOrderListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryOrderListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryOrderListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryOrderListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryOrderListRequestValidationError) ErrorName() string {
	return "QueryOrderListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryOrderListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryOrderListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryOrderListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryOrderListRequestValidationError{}

// Validate checks the field values on PreCreateOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PreCreateOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreCreateOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PreCreateOrderRequestMultiError, or nil if none found.
func (m *PreCreateOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PreCreateOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubscribeId

	// no validation rules for Quantity

	// no validation rules for Payment

	// no validation rules for Coupon

	// no validation rules for PriceOptionId

	// no validation rules for Type

	if len(errors) > 0 {
		return PreCreateOrderRequestMultiError(errors)
	}

	return nil
}

// PreCreateOrderRequestMultiError is an error wrapping multiple validation
// errors returned by PreCreateOrderRequest.ValidateAll() if the designated
// constraints aren't met.
type PreCreateOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreCreateOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreCreateOrderRequestMultiError) AllErrors() []error { return m }

// PreCreateOrderRequestValidationError is the validation error returned by
// PreCreateOrderRequest.Validate if the designated constraints aren't met.
type PreCreateOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreCreateOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreCreateOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreCreateOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreCreateOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreCreateOrderRequestValidationError) ErrorName() string {
	return "PreCreateOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PreCreateOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreCreateOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreCreateOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreCreateOrderRequestValidationError{}

// Validate checks the field values on PreCreateOrderReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PreCreateOrderReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreCreateOrderReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PreCreateOrderReplyMultiError, or nil if none found.
func (m *PreCreateOrderReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PreCreateOrderReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Price

	// no validation rules for Amount

	// no validation rules for Discount

	// no validation rules for GiftAmount

	// no validation rules for Coupon

	// no validation rules for CouponDiscount

	// no validation rules for FeeAmount

	if len(errors) > 0 {
		return PreCreateOrderReplyMultiError(errors)
	}

	return nil
}

// PreCreateOrderReplyMultiError is an error wrapping multiple validation
// errors returned by PreCreateOrderReply.ValidateAll() if the designated
// constraints aren't met.
type PreCreateOrderReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreCreateOrderReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreCreateOrderReplyMultiError) AllErrors() []error { return m }

// PreCreateOrderReplyValidationError is the validation error returned by
// PreCreateOrderReply.Validate if the designated constraints aren't met.
type PreCreateOrderReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreCreateOrderReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreCreateOrderReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreCreateOrderReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreCreateOrderReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreCreateOrderReplyValidationError) ErrorName() string {
	return "PreCreateOrderReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PreCreateOrderReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreCreateOrderReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreCreateOrderReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreCreateOrderReplyValidationError{}

// Validate checks the field values on PurchaseRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PurchaseRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PurchaseRequestMultiError, or nil if none found.
func (m *PurchaseRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubscribeId

	// no validation rules for Quantity

	// no validation rules for Payment

	// no validation rules for Coupon

	// no validation rules for PriceOptionId

	if len(errors) > 0 {
		return PurchaseRequestMultiError(errors)
	}

	return nil
}

// PurchaseRequestMultiError is an error wrapping multiple validation errors
// returned by PurchaseRequest.ValidateAll() if the designated constraints
// aren't met.
type PurchaseRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseRequestMultiError) AllErrors() []error { return m }

// PurchaseRequestValidationError is the validation error returned by
// PurchaseRequest.Validate if the designated constraints aren't met.
type PurchaseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseRequestValidationError) ErrorName() string { return "PurchaseRequestValidationError" }

// Error satisfies the builtin error interface
func (e PurchaseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseRequestValidationError{}

// Validate checks the field values on PurchaseReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PurchaseReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PurchaseReplyMultiError, or
// nil if none found.
func (m *PurchaseReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	if len(errors) > 0 {
		return PurchaseReplyMultiError(errors)
	}

	return nil
}

// PurchaseReplyMultiError is an error wrapping multiple validation errors
// returned by PurchaseReply.ValidateAll() if the designated constraints
// aren't met.
type PurchaseReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseReplyMultiError) AllErrors() []error { return m }

// PurchaseReplyValidationError is the validation error returned by
// PurchaseReply.Validate if the designated constraints aren't met.
type PurchaseReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseReplyValidationError) ErrorName() string { return "PurchaseReplyValidationError" }

// Error satisfies the builtin error interface
func (e PurchaseReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseReplyValidationError{}

// Validate checks the field values on RechargeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RechargeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RechargeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RechargeRequestMultiError, or nil if none found.
func (m *RechargeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RechargeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Amount

	// no validation rules for Payment

	if len(errors) > 0 {
		return RechargeRequestMultiError(errors)
	}

	return nil
}

// RechargeRequestMultiError is an error wrapping multiple validation errors
// returned by RechargeRequest.ValidateAll() if the designated constraints
// aren't met.
type RechargeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RechargeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RechargeRequestMultiError) AllErrors() []error { return m }

// RechargeRequestValidationError is the validation error returned by
// RechargeRequest.Validate if the designated constraints aren't met.
type RechargeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RechargeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RechargeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RechargeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RechargeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RechargeRequestValidationError) ErrorName() string { return "RechargeRequestValidationError" }

// Error satisfies the builtin error interface
func (e RechargeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRechargeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RechargeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RechargeRequestValidationError{}

// Validate checks the field values on RechargeReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RechargeReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RechargeReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RechargeReplyMultiError, or
// nil if none found.
func (m *RechargeReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RechargeReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	if len(errors) > 0 {
		return RechargeReplyMultiError(errors)
	}

	return nil
}

// RechargeReplyMultiError is an error wrapping multiple validation errors
// returned by RechargeReply.ValidateAll() if the designated constraints
// aren't met.
type RechargeReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RechargeReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RechargeReplyMultiError) AllErrors() []error { return m }

// RechargeReplyValidationError is the validation error returned by
// RechargeReply.Validate if the designated constraints aren't met.
type RechargeReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RechargeReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RechargeReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RechargeReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RechargeReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RechargeReplyValidationError) ErrorName() string { return "RechargeReplyValidationError" }

// Error satisfies the builtin error interface
func (e RechargeReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRechargeReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RechargeReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RechargeReplyValidationError{}

// Validate checks the field values on RenewalRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RenewalRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RenewalRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RenewalRequestMultiError,
// or nil if none found.
func (m *RenewalRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RenewalRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserSubscribeId

	// no validation rules for Quantity

	// no validation rules for Payment

	// no validation rules for Coupon

	// no validation rules for PriceOptionId

	if len(errors) > 0 {
		return RenewalRequestMultiError(errors)
	}

	return nil
}

// RenewalRequestMultiError is an error wrapping multiple validation errors
// returned by RenewalRequest.ValidateAll() if the designated constraints
// aren't met.
type RenewalRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RenewalRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RenewalRequestMultiError) AllErrors() []error { return m }

// RenewalRequestValidationError is the validation error returned by
// RenewalRequest.Validate if the designated constraints aren't met.
type RenewalRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RenewalRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RenewalRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RenewalRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RenewalRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RenewalRequestValidationError) ErrorName() string { return "RenewalRequestValidationError" }

// Error satisfies the builtin error interface
func (e RenewalRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRenewalRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RenewalRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RenewalRequestValidationError{}

// Validate checks the field values on RenewalReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RenewalReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RenewalReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RenewalReplyMultiError, or
// nil if none found.
func (m *RenewalReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RenewalReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	if len(errors) > 0 {
		return RenewalReplyMultiError(errors)
	}

	return nil
}

// RenewalReplyMultiError is an error wrapping multiple validation errors
// returned by RenewalReply.ValidateAll() if the designated constraints aren't met.
type RenewalReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RenewalReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RenewalReplyMultiError) AllErrors() []error { return m }

// RenewalReplyValidationError is the validation error returned by
// RenewalReply.Validate if the designated constraints aren't met.
type RenewalReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RenewalReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RenewalReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RenewalReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RenewalReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RenewalReplyValidationError) ErrorName() string { return "RenewalReplyValidationError" }

// Error satisfies the builtin error interface
func (e RenewalReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRenewalReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RenewalReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RenewalReplyValidationError{}

// Validate checks the field values on ResetTrafficRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetTrafficRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetTrafficRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResetTrafficRequestMultiError, or nil if none found.
func (m *ResetTrafficRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetTrafficRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserSubscribeId

	// no validation rules for Payment

	if len(errors) > 0 {
		return ResetTrafficRequestMultiError(errors)
	}

	return nil
}

// ResetTrafficRequestMultiError is an error wrapping multiple validation
// errors returned by ResetTrafficRequest.ValidateAll() if the designated
// constraints aren't met.
type ResetTrafficRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetTrafficRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetTrafficRequestMultiError) AllErrors() []error { return m }

// ResetTrafficRequestValidationError is the validation error returned by
// ResetTrafficRequest.Validate if the designated constraints aren't met.
type ResetTrafficRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetTrafficRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetTrafficRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetTrafficRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetTrafficRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetTrafficRequestValidationError) ErrorName() string {
	return "ResetTrafficRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResetTrafficRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetTrafficRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetTrafficRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetTrafficRequestValidationError{}

// Validate checks the field values on ResetTrafficReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ResetTrafficReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetTrafficReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResetTrafficReplyMultiError, or nil if none found.
func (m *ResetTrafficReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetTrafficReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	if len(errors) > 0 {
		return ResetTrafficReplyMultiError(errors)
	}

	return nil
}

// ResetTrafficReplyMultiError is an error wrapping multiple validation errors
// returned by ResetTrafficReply.ValidateAll() if the designated constraints
// aren't met.
type ResetTrafficReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetTrafficReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetTrafficReplyMultiError) AllErrors() []error { return m }

// ResetTrafficReplyValidationError is the validation error returned by
// ResetTrafficReply.Validate if the designated constraints aren't met.
type ResetTrafficReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetTrafficReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetTrafficReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetTrafficReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetTrafficReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetTrafficReplyValidationError) ErrorName() string {
	return "ResetTrafficReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ResetTrafficReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetTrafficReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetTrafficReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetTrafficReplyValidationError{}

// Validate checks the field values on QueryOrderListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryOrderListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryOrderListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryOrderListReplyMultiError, or nil if none found.
func (m *QueryOrderListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryOrderListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryOrderListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryOrderListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryOrderListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return QueryOrderListReplyMultiError(errors)
	}

	return nil
}

// QueryOrderListReplyMultiError is an error wrapping multiple validation
// errors returned by QueryOrderListReply.ValidateAll() if the designated
// constraints aren't met.
type QueryOrderListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryOrderListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryOrderListReplyMultiError) AllErrors() []error { return m }

// QueryOrderListReplyValidationError is the validation error returned by
// QueryOrderListReply.Validate if the designated constraints aren't met.
type QueryOrderListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryOrderListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryOrderListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryOrderListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryOrderListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryOrderListReplyValidationError) ErrorName() string {
	return "QueryOrderListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryOrderListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryOrderListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryOrderListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryOrderListReplyValidationError{}

// Validate checks the field values on PaymentMethod with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PaymentMethod) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentMethod with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaymentMethodMultiError, or
// nil if none found.
func (m *PaymentMethod) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentMethod) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Platform

	// no validation rules for Description

	// no validation rules for Icon

	// no validation rules for FeeMode

	// no validation rules for FeePercent

	// no validation rules for FeeAmount

	if len(errors) > 0 {
		return PaymentMethodMultiError(errors)
	}

	return nil
}

// PaymentMethodMultiError is an error wrapping multiple validation errors
// returned by PaymentMethod.ValidateAll() if the designated constraints
// aren't met.
type PaymentMethodMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentMethodMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentMethodMultiError) AllErrors() []error { return m }

// PaymentMethodValidationError is the validation error returned by
// PaymentMethod.Validate if the designated constraints aren't met.
type PaymentMethodValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentMethodValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentMethodValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentMethodValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentMethodValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentMethodValidationError) ErrorName() string { return "PaymentMethodValidationError" }

// Error satisfies the builtin error interface
func (e PaymentMethodValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentMethod.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentMethodValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentMethodValidationError{}

// Validate checks the field values on SubscribeDiscount with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SubscribeDiscount) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscribeDiscount with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubscribeDiscountMultiError, or nil if none found.
func (m *SubscribeDiscount) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscribeDiscount) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Quantity

	// no validation rules for Discount

	if len(errors) > 0 {
		return SubscribeDiscountMultiError(errors)
	}

	return nil
}

// SubscribeDiscountMultiError is an error wrapping multiple validation errors
// returned by SubscribeDiscount.ValidateAll() if the designated constraints
// aren't met.
type SubscribeDiscountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscribeDiscountMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscribeDiscountMultiError) AllErrors() []error { return m }

// SubscribeDiscountValidationError is the validation error returned by
// SubscribeDiscount.Validate if the designated constraints aren't met.
type SubscribeDiscountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscribeDiscountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscribeDiscountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscribeDiscountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscribeDiscountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscribeDiscountValidationError) ErrorName() string {
	return "SubscribeDiscountValidationError"
}

// Error satisfies the builtin error interface
func (e SubscribeDiscountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscribeDiscount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscribeDiscountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscribeDiscountValidationError{}

// Validate checks the field values on TrafficLimit with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TrafficLimit) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrafficLimit with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TrafficLimitMultiError, or
// nil if none found.
func (m *TrafficLimit) ValidateAll() error {
	return m.validate(true)
}

func (m *TrafficLimit) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StatType

	// no validation rules for StatValue

	// no validation rules for TrafficUsage

	// no validation rules for SpeedLimit

	if len(errors) > 0 {
		return TrafficLimitMultiError(errors)
	}

	return nil
}

// TrafficLimitMultiError is an error wrapping multiple validation errors
// returned by TrafficLimit.ValidateAll() if the designated constraints aren't met.
type TrafficLimitMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrafficLimitMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrafficLimitMultiError) AllErrors() []error { return m }

// TrafficLimitValidationError is the validation error returned by
// TrafficLimit.Validate if the designated constraints aren't met.
type TrafficLimitValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrafficLimitValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrafficLimitValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrafficLimitValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrafficLimitValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrafficLimitValidationError) ErrorName() string { return "TrafficLimitValidationError" }

// Error satisfies the builtin error interface
func (e TrafficLimitValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrafficLimit.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrafficLimitValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrafficLimitValidationError{}

// Validate checks the field values on SubscribePriceOption with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubscribePriceOption) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscribePriceOption with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubscribePriceOptionMultiError, or nil if none found.
func (m *SubscribePriceOption) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscribePriceOption) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SubscribeId

	// no validation rules for Name

	// no validation rules for DurationUnit

	// no validation rules for DurationValue

	// no validation rules for Price

	// no validation rules for OriginalPrice

	// no validation rules for Inventory

	// no validation rules for Show

	// no validation rules for Sell

	// no validation rules for IsDefault

	// no validation rules for Sort

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return SubscribePriceOptionMultiError(errors)
	}

	return nil
}

// SubscribePriceOptionMultiError is an error wrapping multiple validation
// errors returned by SubscribePriceOption.ValidateAll() if the designated
// constraints aren't met.
type SubscribePriceOptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscribePriceOptionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscribePriceOptionMultiError) AllErrors() []error { return m }

// SubscribePriceOptionValidationError is the validation error returned by
// SubscribePriceOption.Validate if the designated constraints aren't met.
type SubscribePriceOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscribePriceOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscribePriceOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscribePriceOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscribePriceOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscribePriceOptionValidationError) ErrorName() string {
	return "SubscribePriceOptionValidationError"
}

// Error satisfies the builtin error interface
func (e SubscribePriceOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscribePriceOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscribePriceOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscribePriceOptionValidationError{}

// Validate checks the field values on Subscribe with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Subscribe) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Subscribe with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SubscribeMultiError, or nil
// if none found.
func (m *Subscribe) ValidateAll() error {
	return m.validate(true)
}

func (m *Subscribe) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Language

	// no validation rules for Description

	// no validation rules for UnitPrice

	// no validation rules for UnitTime

	for idx, item := range m.GetDiscount() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SubscribeValidationError{
						field:  fmt.Sprintf("Discount[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SubscribeValidationError{
						field:  fmt.Sprintf("Discount[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SubscribeValidationError{
					field:  fmt.Sprintf("Discount[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Replacement

	// no validation rules for Inventory

	// no validation rules for Traffic

	// no validation rules for SpeedLimit

	// no validation rules for DeviceLimit

	// no validation rules for Quota

	// no validation rules for CategoryId

	// no validation rules for CategoryName

	// no validation rules for NodeGroupId

	for idx, item := range m.GetTrafficLimit() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SubscribeValidationError{
						field:  fmt.Sprintf("TrafficLimit[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SubscribeValidationError{
						field:  fmt.Sprintf("TrafficLimit[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SubscribeValidationError{
					field:  fmt.Sprintf("TrafficLimit[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Show

	// no validation rules for Sell

	// no validation rules for Sort

	// no validation rules for DeductionRatio

	// no validation rules for AllowDeduction

	// no validation rules for ResetCycle

	// no validation rules for RenewalReset

	// no validation rules for ShowOriginalPrice

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	for idx, item := range m.GetPriceOptions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SubscribeValidationError{
						field:  fmt.Sprintf("PriceOptions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SubscribeValidationError{
						field:  fmt.Sprintf("PriceOptions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SubscribeValidationError{
					field:  fmt.Sprintf("PriceOptions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SubscribeMultiError(errors)
	}

	return nil
}

// SubscribeMultiError is an error wrapping multiple validation errors returned
// by Subscribe.ValidateAll() if the designated constraints aren't met.
type SubscribeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscribeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscribeMultiError) AllErrors() []error { return m }

// SubscribeValidationError is the validation error returned by
// Subscribe.Validate if the designated constraints aren't met.
type SubscribeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscribeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscribeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscribeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscribeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscribeValidationError) ErrorName() string { return "SubscribeValidationError" }

// Error satisfies the builtin error interface
func (e SubscribeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscribe.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscribeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscribeValidationError{}

// Validate checks the field values on OrderDetail with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderDetail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderDetail with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderDetailMultiError, or
// nil if none found.
func (m *OrderDetail) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderDetail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for OrderNo

	// no validation rules for Type

	// no validation rules for Quantity

	// no validation rules for Price

	// no validation rules for Amount

	// no validation rules for GiftAmount

	// no validation rules for Discount

	// no validation rules for Coupon

	// no validation rules for CouponDiscount

	// no validation rules for Commission

	if all {
		switch v := interface{}(m.GetPayment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderDetailValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderDetailValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPayment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderDetailValidationError{
				field:  "Payment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Method

	// no validation rules for FeeAmount

	// no validation rules for TradeNo

	// no validation rules for Status

	// no validation rules for SubscribeId

	if all {
		switch v := interface{}(m.GetSubscribe()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderDetailValidationError{
					field:  "Subscribe",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderDetailValidationError{
					field:  "Subscribe",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSubscribe()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderDetailValidationError{
				field:  "Subscribe",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for PriceOptionId

	// no validation rules for PriceOptionName

	// no validation rules for DurationUnit

	// no validation rules for DurationValue

	// no validation rules for OptionPrice

	if len(errors) > 0 {
		return OrderDetailMultiError(errors)
	}

	return nil
}

// OrderDetailMultiError is an error wrapping multiple validation errors
// returned by OrderDetail.ValidateAll() if the designated constraints aren't met.
type OrderDetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderDetailMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderDetailMultiError) AllErrors() []error { return m }

// OrderDetailValidationError is the validation error returned by
// OrderDetail.Validate if the designated constraints aren't met.
type OrderDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderDetailValidationError) ErrorName() string { return "OrderDetailValidationError" }

// Error satisfies the builtin error interface
func (e OrderDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderDetailValidationError{}
