// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/npanel-dev/NPanel-backend/ent/predicate"
	"github.com/npanel-dev/NPanel-backend/ent/proxysubscribepriceoption"
)

// ProxySubscribePriceOptionUpdate is the builder for updating ProxySubscribePriceOption entities.
type ProxySubscribePriceOptionUpdate struct {
	config
	hooks    []Hook
	mutation *ProxySubscribePriceOptionMutation
}

// Where appends a list predicates to the ProxySubscribePriceOptionUpdate builder.
func (_u *ProxySubscribePriceOptionUpdate) Where(ps ...predicate.ProxySubscribePriceOption) *ProxySubscribePriceOptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubscribeID sets the "subscribe_id" field.
func (_u *ProxySubscribePriceOptionUpdate) SetSubscribeID(v int64) *ProxySubscribePriceOptionUpdate {
	_u.mutation.ResetSubscribeID()
	_u.mutation.SetSubscribeID(v)
	return _u
}

// SetNillableSubscribeID sets the "subscribe_id" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableSubscribeID(v *int64) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetSubscribeID(*v)
	}
	return _u
}

// AddSubscribeID adds value to the "subscribe_id" field.
func (_u *ProxySubscribePriceOptionUpdate) AddSubscribeID(v int64) *ProxySubscribePriceOptionUpdate {
	_u.mutation.AddSubscribeID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxySubscribePriceOptionUpdate) SetName(v string) *ProxySubscribePriceOptionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableName(v *string) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDurationUnit sets the "duration_unit" field.
func (_u *ProxySubscribePriceOptionUpdate) SetDurationUnit(v string) *ProxySubscribePriceOptionUpdate {
	_u.mutation.SetDurationUnit(v)
	return _u
}

// SetNillableDurationUnit sets the "duration_unit" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableDurationUnit(v *string) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetDurationUnit(*v)
	}
	return _u
}

// SetDurationValue sets the "duration_value" field.
func (_u *ProxySubscribePriceOptionUpdate) SetDurationValue(v int64) *ProxySubscribePriceOptionUpdate {
	_u.mutation.ResetDurationValue()
	_u.mutation.SetDurationValue(v)
	return _u
}

// SetNillableDurationValue sets the "duration_value" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableDurationValue(v *int64) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetDurationValue(*v)
	}
	return _u
}

// AddDurationValue adds value to the "duration_value" field.
func (_u *ProxySubscribePriceOptionUpdate) AddDurationValue(v int64) *ProxySubscribePriceOptionUpdate {
	_u.mutation.AddDurationValue(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *ProxySubscribePriceOptionUpdate) SetPrice(v int64) *ProxySubscribePriceOptionUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillablePrice(v *int64) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *ProxySubscribePriceOptionUpdate) AddPrice(v int64) *ProxySubscribePriceOptionUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *ProxySubscribePriceOptionUpdate) SetOriginalPrice(v int64) *ProxySubscribePriceOptionUpdate {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableOriginalPrice(v *int64) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *ProxySubscribePriceOptionUpdate) AddOriginalPrice(v int64) *ProxySubscribePriceOptionUpdate {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// SetInventory sets the "inventory" field.
func (_u *ProxySubscribePriceOptionUpdate) SetInventory(v int32) *ProxySubscribePriceOptionUpdate {
	_u.mutation.ResetInventory()
	_u.mutation.SetInventory(v)
	return _u
}

// SetNillableInventory sets the "inventory" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableInventory(v *int32) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetInventory(*v)
	}
	return _u
}

// AddInventory adds value to the "inventory" field.
func (_u *ProxySubscribePriceOptionUpdate) AddInventory(v int32) *ProxySubscribePriceOptionUpdate {
	_u.mutation.AddInventory(v)
	return _u
}

// SetShow sets the "show" field.
func (_u *ProxySubscribePriceOptionUpdate) SetShow(v bool) *ProxySubscribePriceOptionUpdate {
	_u.mutation.SetShow(v)
	return _u
}

// SetNillableShow sets the "show" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableShow(v *bool) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetShow(*v)
	}
	return _u
}

// SetSell sets the "sell" field.
func (_u *ProxySubscribePriceOptionUpdate) SetSell(v bool) *ProxySubscribePriceOptionUpdate {
	_u.mutation.SetSell(v)
	return _u
}

// SetNillableSell sets the "sell" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableSell(v *bool) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetSell(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *ProxySubscribePriceOptionUpdate) SetIsDefault(v bool) *ProxySubscribePriceOptionUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableIsDefault(v *bool) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *ProxySubscribePriceOptionUpdate) SetSort(v int32) *ProxySubscribePriceOptionUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdate) SetNillableSort(v *int32) *ProxySubscribePriceOptionUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *ProxySubscribePriceOptionUpdate) AddSort(v int32) *ProxySubscribePriceOptionUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySubscribePriceOptionUpdate) SetUpdatedAt(v time.Time) *ProxySubscribePriceOptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxySubscribePriceOptionMutation object of the builder.
func (_u *ProxySubscribePriceOptionUpdate) Mutation() *ProxySubscribePriceOptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxySubscribePriceOptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySubscribePriceOptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxySubscribePriceOptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySubscribePriceOptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySubscribePriceOptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxysubscribepriceoption.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySubscribePriceOptionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxysubscribepriceoption.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribePriceOption.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationUnit(); ok {
		if err := proxysubscribepriceoption.DurationUnitValidator(v); err != nil {
			return &ValidationError{Name: "duration_unit", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribePriceOption.duration_unit": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySubscribePriceOptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysubscribepriceoption.Table, proxysubscribepriceoption.Columns, sqlgraph.NewFieldSpec(proxysubscribepriceoption.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubscribeID(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscribeID(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationUnit(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldDurationUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationValue(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldDurationValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationValue(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldDurationValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldOriginalPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldOriginalPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Inventory(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldInventory, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedInventory(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldInventory, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Show(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldShow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sell(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldSell, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysubscribepriceoption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxySubscribePriceOptionUpdateOne is the builder for updating a single ProxySubscribePriceOption entity.
type ProxySubscribePriceOptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxySubscribePriceOptionMutation
}

// SetSubscribeID sets the "subscribe_id" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetSubscribeID(v int64) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.ResetSubscribeID()
	_u.mutation.SetSubscribeID(v)
	return _u
}

// SetNillableSubscribeID sets the "subscribe_id" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableSubscribeID(v *int64) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetSubscribeID(*v)
	}
	return _u
}

// AddSubscribeID adds value to the "subscribe_id" field.
func (_u *ProxySubscribePriceOptionUpdateOne) AddSubscribeID(v int64) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.AddSubscribeID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetName(v string) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableName(v *string) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDurationUnit sets the "duration_unit" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetDurationUnit(v string) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.SetDurationUnit(v)
	return _u
}

// SetNillableDurationUnit sets the "duration_unit" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableDurationUnit(v *string) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetDurationUnit(*v)
	}
	return _u
}

// SetDurationValue sets the "duration_value" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetDurationValue(v int64) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.ResetDurationValue()
	_u.mutation.SetDurationValue(v)
	return _u
}

// SetNillableDurationValue sets the "duration_value" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableDurationValue(v *int64) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetDurationValue(*v)
	}
	return _u
}

// AddDurationValue adds value to the "duration_value" field.
func (_u *ProxySubscribePriceOptionUpdateOne) AddDurationValue(v int64) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.AddDurationValue(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetPrice(v int64) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillablePrice(v *int64) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *ProxySubscribePriceOptionUpdateOne) AddPrice(v int64) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetOriginalPrice(v int64) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableOriginalPrice(v *int64) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *ProxySubscribePriceOptionUpdateOne) AddOriginalPrice(v int64) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// SetInventory sets the "inventory" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetInventory(v int32) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.ResetInventory()
	_u.mutation.SetInventory(v)
	return _u
}

// SetNillableInventory sets the "inventory" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableInventory(v *int32) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetInventory(*v)
	}
	return _u
}

// AddInventory adds value to the "inventory" field.
func (_u *ProxySubscribePriceOptionUpdateOne) AddInventory(v int32) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.AddInventory(v)
	return _u
}

// SetShow sets the "show" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetShow(v bool) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.SetShow(v)
	return _u
}

// SetNillableShow sets the "show" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableShow(v *bool) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetShow(*v)
	}
	return _u
}

// SetSell sets the "sell" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetSell(v bool) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.SetSell(v)
	return _u
}

// SetNillableSell sets the "sell" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableSell(v *bool) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetSell(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetIsDefault(v bool) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableIsDefault(v *bool) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetSort(v int32) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *ProxySubscribePriceOptionUpdateOne) SetNillableSort(v *int32) *ProxySubscribePriceOptionUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *ProxySubscribePriceOptionUpdateOne) AddSort(v int32) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySubscribePriceOptionUpdateOne) SetUpdatedAt(v time.Time) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxySubscribePriceOptionMutation object of the builder.
func (_u *ProxySubscribePriceOptionUpdateOne) Mutation() *ProxySubscribePriceOptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxySubscribePriceOptionUpdate builder.
func (_u *ProxySubscribePriceOptionUpdateOne) Where(ps ...predicate.ProxySubscribePriceOption) *ProxySubscribePriceOptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxySubscribePriceOptionUpdateOne) Select(field string, fields ...string) *ProxySubscribePriceOptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxySubscribePriceOption entity.
func (_u *ProxySubscribePriceOptionUpdateOne) Save(ctx context.Context) (*ProxySubscribePriceOption, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySubscribePriceOptionUpdateOne) SaveX(ctx context.Context) *ProxySubscribePriceOption {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxySubscribePriceOptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySubscribePriceOptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySubscribePriceOptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxysubscribepriceoption.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySubscribePriceOptionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxysubscribepriceoption.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribePriceOption.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationUnit(); ok {
		if err := proxysubscribepriceoption.DurationUnitValidator(v); err != nil {
			return &ValidationError{Name: "duration_unit", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribePriceOption.duration_unit": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySubscribePriceOptionUpdateOne) sqlSave(ctx context.Context) (_node *ProxySubscribePriceOption, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysubscribepriceoption.Table, proxysubscribepriceoption.Columns, sqlgraph.NewFieldSpec(proxysubscribepriceoption.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxySubscribePriceOption.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxysubscribepriceoption.FieldID)
		for _, f := range fields {
			if !proxysubscribepriceoption.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxysubscribepriceoption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubscribeID(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscribeID(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationUnit(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldDurationUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationValue(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldDurationValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationValue(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldDurationValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldOriginalPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldOriginalPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Inventory(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldInventory, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedInventory(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldInventory, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Show(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldShow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sell(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldSell, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(proxysubscribepriceoption.FieldSort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProxySubscribePriceOption{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysubscribepriceoption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
