// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/npanel-dev/NPanel-backend/ent/proxysubscribepriceoption"
)

// ProxySubscribePriceOptionCreate is the builder for creating a ProxySubscribePriceOption entity.
type ProxySubscribePriceOptionCreate struct {
	config
	mutation *ProxySubscribePriceOptionMutation
	hooks    []Hook
}

// SetSubscribeID sets the "subscribe_id" field.
func (_c *ProxySubscribePriceOptionCreate) SetSubscribeID(v int64) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetSubscribeID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ProxySubscribePriceOptionCreate) SetName(v string) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableName(v *string) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDurationUnit sets the "duration_unit" field.
func (_c *ProxySubscribePriceOptionCreate) SetDurationUnit(v string) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetDurationUnit(v)
	return _c
}

// SetNillableDurationUnit sets the "duration_unit" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableDurationUnit(v *string) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetDurationUnit(*v)
	}
	return _c
}

// SetDurationValue sets the "duration_value" field.
func (_c *ProxySubscribePriceOptionCreate) SetDurationValue(v int64) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetDurationValue(v)
	return _c
}

// SetNillableDurationValue sets the "duration_value" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableDurationValue(v *int64) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetDurationValue(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *ProxySubscribePriceOptionCreate) SetPrice(v int64) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillablePrice(v *int64) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetOriginalPrice sets the "original_price" field.
func (_c *ProxySubscribePriceOptionCreate) SetOriginalPrice(v int64) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetOriginalPrice(v)
	return _c
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableOriginalPrice(v *int64) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetOriginalPrice(*v)
	}
	return _c
}

// SetInventory sets the "inventory" field.
func (_c *ProxySubscribePriceOptionCreate) SetInventory(v int32) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetInventory(v)
	return _c
}

// SetNillableInventory sets the "inventory" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableInventory(v *int32) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetInventory(*v)
	}
	return _c
}

// SetShow sets the "show" field.
func (_c *ProxySubscribePriceOptionCreate) SetShow(v bool) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetShow(v)
	return _c
}

// SetNillableShow sets the "show" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableShow(v *bool) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetShow(*v)
	}
	return _c
}

// SetSell sets the "sell" field.
func (_c *ProxySubscribePriceOptionCreate) SetSell(v bool) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetSell(v)
	return _c
}

// SetNillableSell sets the "sell" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableSell(v *bool) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetSell(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *ProxySubscribePriceOptionCreate) SetIsDefault(v bool) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableIsDefault(v *bool) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *ProxySubscribePriceOptionCreate) SetSort(v int32) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableSort(v *int32) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxySubscribePriceOptionCreate) SetCreatedAt(v time.Time) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableCreatedAt(v *time.Time) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxySubscribePriceOptionCreate) SetUpdatedAt(v time.Time) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxySubscribePriceOptionCreate) SetNillableUpdatedAt(v *time.Time) *ProxySubscribePriceOptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProxySubscribePriceOptionCreate) SetID(v int64) *ProxySubscribePriceOptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProxySubscribePriceOptionMutation object of the builder.
func (_c *ProxySubscribePriceOptionCreate) Mutation() *ProxySubscribePriceOptionMutation {
	return _c.mutation
}

// Save creates the ProxySubscribePriceOption in the database.
func (_c *ProxySubscribePriceOptionCreate) Save(ctx context.Context) (*ProxySubscribePriceOption, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxySubscribePriceOptionCreate) SaveX(ctx context.Context) *ProxySubscribePriceOption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySubscribePriceOptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySubscribePriceOptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxySubscribePriceOptionCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := proxysubscribepriceoption.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.DurationUnit(); !ok {
		v := proxysubscribepriceoption.DefaultDurationUnit
		_c.mutation.SetDurationUnit(v)
	}
	if _, ok := _c.mutation.DurationValue(); !ok {
		v := proxysubscribepriceoption.DefaultDurationValue
		_c.mutation.SetDurationValue(v)
	}
	if _, ok := _c.mutation.Price(); !ok {
		v := proxysubscribepriceoption.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.OriginalPrice(); !ok {
		v := proxysubscribepriceoption.DefaultOriginalPrice
		_c.mutation.SetOriginalPrice(v)
	}
	if _, ok := _c.mutation.Inventory(); !ok {
		v := proxysubscribepriceoption.DefaultInventory
		_c.mutation.SetInventory(v)
	}
	if _, ok := _c.mutation.Show(); !ok {
		v := proxysubscribepriceoption.DefaultShow
		_c.mutation.SetShow(v)
	}
	if _, ok := _c.mutation.Sell(); !ok {
		v := proxysubscribepriceoption.DefaultSell
		_c.mutation.SetSell(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := proxysubscribepriceoption.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := proxysubscribepriceoption.DefaultSort
		_c.mutation.SetSort(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxysubscribepriceoption.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxysubscribepriceoption.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxySubscribePriceOptionCreate) check() error {
	if _, ok := _c.mutation.SubscribeID(); !ok {
		return &ValidationError{Name: "subscribe_id", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.subscribe_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxysubscribepriceoption.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribePriceOption.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationUnit(); !ok {
		return &ValidationError{Name: "duration_unit", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.duration_unit"`)}
	}
	if v, ok := _c.mutation.DurationUnit(); ok {
		if err := proxysubscribepriceoption.DurationUnitValidator(v); err != nil {
			return &ValidationError{Name: "duration_unit", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribePriceOption.duration_unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationValue(); !ok {
		return &ValidationError{Name: "duration_value", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.duration_value"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.price"`)}
	}
	if _, ok := _c.mutation.OriginalPrice(); !ok {
		return &ValidationError{Name: "original_price", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.original_price"`)}
	}
	if _, ok := _c.mutation.Inventory(); !ok {
		return &ValidationError{Name: "inventory", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.inventory"`)}
	}
	if _, ok := _c.mutation.Show(); !ok {
		return &ValidationError{Name: "show", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.show"`)}
	}
	if _, ok := _c.mutation.Sell(); !ok {
		return &ValidationError{Name: "sell", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.sell"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.is_default"`)}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.sort"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxySubscribePriceOption.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := proxysubscribepriceoption.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribePriceOption.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ProxySubscribePriceOptionCreate) sqlSave(ctx context.Context) (*ProxySubscribePriceOption, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxySubscribePriceOptionCreate) createSpec() (*ProxySubscribePriceOption, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxySubscribePriceOption{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxysubscribepriceoption.Table, sqlgraph.NewFieldSpec(proxysubscribepriceoption.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SubscribeID(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldSubscribeID, field.TypeInt64, value)
		_node.SubscribeID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DurationUnit(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldDurationUnit, field.TypeString, value)
		_node.DurationUnit = value
	}
	if value, ok := _c.mutation.DurationValue(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldDurationValue, field.TypeInt64, value)
		_node.DurationValue = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldPrice, field.TypeInt64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.OriginalPrice(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldOriginalPrice, field.TypeInt64, value)
		_node.OriginalPrice = value
	}
	if value, ok := _c.mutation.Inventory(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldInventory, field.TypeInt32, value)
		_node.Inventory = value
	}
	if value, ok := _c.mutation.Show(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldShow, field.TypeBool, value)
		_node.Show = value
	}
	if value, ok := _c.mutation.Sell(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldSell, field.TypeBool, value)
		_node.Sell = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldSort, field.TypeInt32, value)
		_node.Sort = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscribepriceoption.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ProxySubscribePriceOptionCreateBulk is the builder for creating many ProxySubscribePriceOption entities in bulk.
type ProxySubscribePriceOptionCreateBulk struct {
	config
	err      error
	builders []*ProxySubscribePriceOptionCreate
}

// Save creates the ProxySubscribePriceOption entities in the database.
func (_c *ProxySubscribePriceOptionCreateBulk) Save(ctx context.Context) ([]*ProxySubscribePriceOption, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxySubscribePriceOption, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxySubscribePriceOptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxySubscribePriceOptionCreateBulk) SaveX(ctx context.Context) []*ProxySubscribePriceOption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySubscribePriceOptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySubscribePriceOptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
