// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/npanel-dev/NPanel-backend/ent/proxyorder"
)

// ProxyOrderCreate is the builder for creating a ProxyOrder entity.
type ProxyOrderCreate struct {
	config
	mutation *ProxyOrderMutation
	hooks    []Hook
}

// SetParentID sets the "parent_id" field.
func (_c *ProxyOrderCreate) SetParentID(v int64) *ProxyOrderCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableParentID(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ProxyOrderCreate) SetUserID(v int64) *ProxyOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableUserID(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *ProxyOrderCreate) SetOrderNo(v string) *ProxyOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ProxyOrderCreate) SetType(v int8) *ProxyOrderCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableType(v *int8) *ProxyOrderCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *ProxyOrderCreate) SetQuantity(v int32) *ProxyOrderCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableQuantity(v *int32) *ProxyOrderCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *ProxyOrderCreate) SetPrice(v int64) *ProxyOrderCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillablePrice(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ProxyOrderCreate) SetAmount(v int64) *ProxyOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableAmount(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetGiftAmount sets the "gift_amount" field.
func (_c *ProxyOrderCreate) SetGiftAmount(v int64) *ProxyOrderCreate {
	_c.mutation.SetGiftAmount(v)
	return _c
}

// SetNillableGiftAmount sets the "gift_amount" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableGiftAmount(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetGiftAmount(*v)
	}
	return _c
}

// SetDiscount sets the "discount" field.
func (_c *ProxyOrderCreate) SetDiscount(v int64) *ProxyOrderCreate {
	_c.mutation.SetDiscount(v)
	return _c
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableDiscount(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetDiscount(*v)
	}
	return _c
}

// SetCoupon sets the "coupon" field.
func (_c *ProxyOrderCreate) SetCoupon(v string) *ProxyOrderCreate {
	_c.mutation.SetCoupon(v)
	return _c
}

// SetNillableCoupon sets the "coupon" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableCoupon(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetCoupon(*v)
	}
	return _c
}

// SetCouponDiscount sets the "coupon_discount" field.
func (_c *ProxyOrderCreate) SetCouponDiscount(v int64) *ProxyOrderCreate {
	_c.mutation.SetCouponDiscount(v)
	return _c
}

// SetNillableCouponDiscount sets the "coupon_discount" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableCouponDiscount(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetCouponDiscount(*v)
	}
	return _c
}

// SetCommission sets the "commission" field.
func (_c *ProxyOrderCreate) SetCommission(v int64) *ProxyOrderCreate {
	_c.mutation.SetCommission(v)
	return _c
}

// SetNillableCommission sets the "commission" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableCommission(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetCommission(*v)
	}
	return _c
}

// SetPaymentID sets the "payment_id" field.
func (_c *ProxyOrderCreate) SetPaymentID(v int64) *ProxyOrderCreate {
	_c.mutation.SetPaymentID(v)
	return _c
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillablePaymentID(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetPaymentID(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *ProxyOrderCreate) SetMethod(v string) *ProxyOrderCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableMethod(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetFeeAmount sets the "fee_amount" field.
func (_c *ProxyOrderCreate) SetFeeAmount(v int64) *ProxyOrderCreate {
	_c.mutation.SetFeeAmount(v)
	return _c
}

// SetNillableFeeAmount sets the "fee_amount" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableFeeAmount(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetFeeAmount(*v)
	}
	return _c
}

// SetTradeNo sets the "trade_no" field.
func (_c *ProxyOrderCreate) SetTradeNo(v string) *ProxyOrderCreate {
	_c.mutation.SetTradeNo(v)
	return _c
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableTradeNo(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetTradeNo(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProxyOrderCreate) SetStatus(v int8) *ProxyOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableStatus(v *int8) *ProxyOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSubscribeID sets the "subscribe_id" field.
func (_c *ProxyOrderCreate) SetSubscribeID(v int64) *ProxyOrderCreate {
	_c.mutation.SetSubscribeID(v)
	return _c
}

// SetNillableSubscribeID sets the "subscribe_id" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableSubscribeID(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetSubscribeID(*v)
	}
	return _c
}

// SetPriceOptionID sets the "price_option_id" field.
func (_c *ProxyOrderCreate) SetPriceOptionID(v int64) *ProxyOrderCreate {
	_c.mutation.SetPriceOptionID(v)
	return _c
}

// SetNillablePriceOptionID sets the "price_option_id" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillablePriceOptionID(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetPriceOptionID(*v)
	}
	return _c
}

// SetPriceOptionName sets the "price_option_name" field.
func (_c *ProxyOrderCreate) SetPriceOptionName(v string) *ProxyOrderCreate {
	_c.mutation.SetPriceOptionName(v)
	return _c
}

// SetNillablePriceOptionName sets the "price_option_name" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillablePriceOptionName(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetPriceOptionName(*v)
	}
	return _c
}

// SetDurationUnit sets the "duration_unit" field.
func (_c *ProxyOrderCreate) SetDurationUnit(v string) *ProxyOrderCreate {
	_c.mutation.SetDurationUnit(v)
	return _c
}

// SetNillableDurationUnit sets the "duration_unit" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableDurationUnit(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetDurationUnit(*v)
	}
	return _c
}

// SetDurationValue sets the "duration_value" field.
func (_c *ProxyOrderCreate) SetDurationValue(v int64) *ProxyOrderCreate {
	_c.mutation.SetDurationValue(v)
	return _c
}

// SetNillableDurationValue sets the "duration_value" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableDurationValue(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetDurationValue(*v)
	}
	return _c
}

// SetOptionPrice sets the "option_price" field.
func (_c *ProxyOrderCreate) SetOptionPrice(v int64) *ProxyOrderCreate {
	_c.mutation.SetOptionPrice(v)
	return _c
}

// SetNillableOptionPrice sets the "option_price" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableOptionPrice(v *int64) *ProxyOrderCreate {
	if v != nil {
		_c.SetOptionPrice(*v)
	}
	return _c
}

// SetSubscribeToken sets the "subscribe_token" field.
func (_c *ProxyOrderCreate) SetSubscribeToken(v string) *ProxyOrderCreate {
	_c.mutation.SetSubscribeToken(v)
	return _c
}

// SetNillableSubscribeToken sets the "subscribe_token" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableSubscribeToken(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetSubscribeToken(*v)
	}
	return _c
}

// SetIsNew sets the "is_new" field.
func (_c *ProxyOrderCreate) SetIsNew(v bool) *ProxyOrderCreate {
	_c.mutation.SetIsNew(v)
	return _c
}

// SetNillableIsNew sets the "is_new" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableIsNew(v *bool) *ProxyOrderCreate {
	if v != nil {
		_c.SetIsNew(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyOrderCreate) SetCreatedAt(v time.Time) *ProxyOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableCreatedAt(v *time.Time) *ProxyOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyOrderCreate) SetUpdatedAt(v time.Time) *ProxyOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableUpdatedAt(v *time.Time) *ProxyOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProxyOrderCreate) SetID(v int64) *ProxyOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProxyOrderMutation object of the builder.
func (_c *ProxyOrderCreate) Mutation() *ProxyOrderMutation {
	return _c.mutation
}

// Save creates the ProxyOrder in the database.
func (_c *ProxyOrderCreate) Save(ctx context.Context) (*ProxyOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyOrderCreate) SaveX(ctx context.Context) *ProxyOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyOrderCreate) defaults() {
	if _, ok := _c.mutation.UserID(); !ok {
		v := proxyorder.DefaultUserID
		_c.mutation.SetUserID(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := proxyorder.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		v := proxyorder.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.Price(); !ok {
		v := proxyorder.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := proxyorder.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.GiftAmount(); !ok {
		v := proxyorder.DefaultGiftAmount
		_c.mutation.SetGiftAmount(v)
	}
	if _, ok := _c.mutation.Discount(); !ok {
		v := proxyorder.DefaultDiscount
		_c.mutation.SetDiscount(v)
	}
	if _, ok := _c.mutation.CouponDiscount(); !ok {
		v := proxyorder.DefaultCouponDiscount
		_c.mutation.SetCouponDiscount(v)
	}
	if _, ok := _c.mutation.Commission(); !ok {
		v := proxyorder.DefaultCommission
		_c.mutation.SetCommission(v)
	}
	if _, ok := _c.mutation.PaymentID(); !ok {
		v := proxyorder.DefaultPaymentID
		_c.mutation.SetPaymentID(v)
	}
	if _, ok := _c.mutation.Method(); !ok {
		v := proxyorder.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.FeeAmount(); !ok {
		v := proxyorder.DefaultFeeAmount
		_c.mutation.SetFeeAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := proxyorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SubscribeID(); !ok {
		v := proxyorder.DefaultSubscribeID
		_c.mutation.SetSubscribeID(v)
	}
	if _, ok := _c.mutation.PriceOptionID(); !ok {
		v := proxyorder.DefaultPriceOptionID
		_c.mutation.SetPriceOptionID(v)
	}
	if _, ok := _c.mutation.PriceOptionName(); !ok {
		v := proxyorder.DefaultPriceOptionName
		_c.mutation.SetPriceOptionName(v)
	}
	if _, ok := _c.mutation.DurationUnit(); !ok {
		v := proxyorder.DefaultDurationUnit
		_c.mutation.SetDurationUnit(v)
	}
	if _, ok := _c.mutation.DurationValue(); !ok {
		v := proxyorder.DefaultDurationValue
		_c.mutation.SetDurationValue(v)
	}
	if _, ok := _c.mutation.OptionPrice(); !ok {
		v := proxyorder.DefaultOptionPrice
		_c.mutation.SetOptionPrice(v)
	}
	if _, ok := _c.mutation.IsNew(); !ok {
		v := proxyorder.DefaultIsNew
		_c.mutation.SetIsNew(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxyorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxyorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyOrderCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ProxyOrder.user_id"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "ProxyOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := proxyorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "ProxyOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ProxyOrder.type"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "ProxyOrder.quantity"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ProxyOrder.price"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ProxyOrder.amount"`)}
	}
	if _, ok := _c.mutation.GiftAmount(); !ok {
		return &ValidationError{Name: "gift_amount", err: errors.New(`ent: missing required field "ProxyOrder.gift_amount"`)}
	}
	if _, ok := _c.mutation.Discount(); !ok {
		return &ValidationError{Name: "discount", err: errors.New(`ent: missing required field "ProxyOrder.discount"`)}
	}
	if v, ok := _c.mutation.Coupon(); ok {
		if err := proxyorder.CouponValidator(v); err != nil {
			return &ValidationError{Name: "coupon", err: fmt.Errorf(`ent: validator failed for field "ProxyOrder.coupon": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CouponDiscount(); !ok {
		return &ValidationError{Name: "coupon_discount", err: errors.New(`ent: missing required field "ProxyOrder.coupon_discount"`)}
	}
	if _, ok := _c.mutation.Commission(); !ok {
		return &ValidationError{Name: "commission", err: errors.New(`ent: missing required field "ProxyOrder.commission"`)}
	}
	if _, ok := _c.mutation.PaymentID(); !ok {
		return &ValidationError{Name: "payment_id", err: errors.New(`ent: missing required field "ProxyOrder.payment_id"`)}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "ProxyOrder.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := proxyorder.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "ProxyOrder.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FeeAmount(); !ok {
		return &ValidationError{Name: "fee_amount", err: errors.New(`ent: missing required field "ProxyOrder.fee_amount"`)}
	}
	if v, ok := _c.mutation.TradeNo(); ok {
		if err := proxyorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "ProxyOrder.trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProxyOrder.status"`)}
	}
	if _, ok := _c.mutation.SubscribeID(); !ok {
		return &ValidationError{Name: "subscribe_id", err: errors.New(`ent: missing required field "ProxyOrder.subscribe_id"`)}
	}
	if _, ok := _c.mutation.PriceOptionID(); !ok {
		return &ValidationError{Name: "price_option_id", err: errors.New(`ent: missing required field "ProxyOrder.price_option_id"`)}
	}
	if _, ok := _c.mutation.PriceOptionName(); !ok {
		return &ValidationError{Name: "price_option_name", err: errors.New(`ent: missing required field "ProxyOrder.price_option_name"`)}
	}
	if v, ok := _c.mutation.PriceOptionName(); ok {
		if err := proxyorder.PriceOptionNameValidator(v); err != nil {
			return &ValidationError{Name: "price_option_name", err: fmt.Errorf(`ent: validator failed for field "ProxyOrder.price_option_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationUnit(); !ok {
		return &ValidationError{Name: "duration_unit", err: errors.New(`ent: missing required field "ProxyOrder.duration_unit"`)}
	}
	if v, ok := _c.mutation.DurationUnit(); ok {
		if err := proxyorder.DurationUnitValidator(v); err != nil {
			return &ValidationError{Name: "duration_unit", err: fmt.Errorf(`ent: validator failed for field "ProxyOrder.duration_unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationValue(); !ok {
		return &ValidationError{Name: "duration_value", err: errors.New(`ent: missing required field "ProxyOrder.duration_value"`)}
	}
	if _, ok := _c.mutation.OptionPrice(); !ok {
		return &ValidationError{Name: "option_price", err: errors.New(`ent: missing required field "ProxyOrder.option_price"`)}
	}
	if v, ok := _c.mutation.SubscribeToken(); ok {
		if err := proxyorder.SubscribeTokenValidator(v); err != nil {
			return &ValidationError{Name: "subscribe_token", err: fmt.Errorf(`ent: validator failed for field "ProxyOrder.subscribe_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsNew(); !ok {
		return &ValidationError{Name: "is_new", err: errors.New(`ent: missing required field "ProxyOrder.is_new"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyOrder.updated_at"`)}
	}
	return nil
}

func (_c *ProxyOrderCreate) sqlSave(ctx context.Context) (*ProxyOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyOrderCreate) createSpec() (*ProxyOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxyorder.Table, sqlgraph.NewFieldSpec(proxyorder.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(proxyorder.FieldParentID, field.TypeInt64, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(proxyorder.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(proxyorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(proxyorder.FieldType, field.TypeInt8, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(proxyorder.FieldQuantity, field.TypeInt32, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(proxyorder.FieldPrice, field.TypeInt64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(proxyorder.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.GiftAmount(); ok {
		_spec.SetField(proxyorder.FieldGiftAmount, field.TypeInt64, value)
		_node.GiftAmount = value
	}
	if value, ok := _c.mutation.Discount(); ok {
		_spec.SetField(proxyorder.FieldDiscount, field.TypeInt64, value)
		_node.Discount = value
	}
	if value, ok := _c.mutation.Coupon(); ok {
		_spec.SetField(proxyorder.FieldCoupon, field.TypeString, value)
		_node.Coupon = value
	}
	if value, ok := _c.mutation.CouponDiscount(); ok {
		_spec.SetField(proxyorder.FieldCouponDiscount, field.TypeInt64, value)
		_node.CouponDiscount = value
	}
	if value, ok := _c.mutation.Commission(); ok {
		_spec.SetField(proxyorder.FieldCommission, field.TypeInt64, value)
		_node.Commission = value
	}
	if value, ok := _c.mutation.PaymentID(); ok {
		_spec.SetField(proxyorder.FieldPaymentID, field.TypeInt64, value)
		_node.PaymentID = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(proxyorder.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.FeeAmount(); ok {
		_spec.SetField(proxyorder.FieldFeeAmount, field.TypeInt64, value)
		_node.FeeAmount = value
	}
	if value, ok := _c.mutation.TradeNo(); ok {
		_spec.SetField(proxyorder.FieldTradeNo, field.TypeString, value)
		_node.TradeNo = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(proxyorder.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SubscribeID(); ok {
		_spec.SetField(proxyorder.FieldSubscribeID, field.TypeInt64, value)
		_node.SubscribeID = value
	}
	if value, ok := _c.mutation.PriceOptionID(); ok {
		_spec.SetField(proxyorder.FieldPriceOptionID, field.TypeInt64, value)
		_node.PriceOptionID = value
	}
	if value, ok := _c.mutation.PriceOptionName(); ok {
		_spec.SetField(proxyorder.FieldPriceOptionName, field.TypeString, value)
		_node.PriceOptionName = value
	}
	if value, ok := _c.mutation.DurationUnit(); ok {
		_spec.SetField(proxyorder.FieldDurationUnit, field.TypeString, value)
		_node.DurationUnit = value
	}
	if value, ok := _c.mutation.DurationValue(); ok {
		_spec.SetField(proxyorder.FieldDurationValue, field.TypeInt64, value)
		_node.DurationValue = value
	}
	if value, ok := _c.mutation.OptionPrice(); ok {
		_spec.SetField(proxyorder.FieldOptionPrice, field.TypeInt64, value)
		_node.OptionPrice = value
	}
	if value, ok := _c.mutation.SubscribeToken(); ok {
		_spec.SetField(proxyorder.FieldSubscribeToken, field.TypeString, value)
		_node.SubscribeToken = value
	}
	if value, ok := _c.mutation.IsNew(); ok {
		_spec.SetField(proxyorder.FieldIsNew, field.TypeBool, value)
		_node.IsNew = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxyorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ProxyOrderCreateBulk is the builder for creating many ProxyOrder entities in bulk.
type ProxyOrderCreateBulk struct {
	config
	err      error
	builders []*ProxyOrderCreate
}

// Save creates the ProxyOrder entities in the database.
func (_c *ProxyOrderCreateBulk) Save(ctx context.Context) ([]*ProxyOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyOrderCreateBulk) SaveX(ctx context.Context) []*ProxyOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
