// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.19.4
// source: public/user/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPublicUserBindOAuth = "/api.public.user.v1.PublicUser/BindOAuth"
const OperationPublicUserBindOAuthCallback = "/api.public.user.v1.PublicUser/BindOAuthCallback"
const OperationPublicUserBindTelegram = "/api.public.user.v1.PublicUser/BindTelegram"
const OperationPublicUserCommissionWithdraw = "/api.public.user.v1.PublicUser/CommissionWithdraw"
const OperationPublicUserDeleteCurrentUserAccount = "/api.public.user.v1.PublicUser/DeleteCurrentUserAccount"
const OperationPublicUserDeviceWSConnect = "/api.public.user.v1.PublicUser/DeviceWSConnect"
const OperationPublicUserGetDeviceList = "/api.public.user.v1.PublicUser/GetDeviceList"
const OperationPublicUserGetDeviceOnlineStatistics = "/api.public.user.v1.PublicUser/GetDeviceOnlineStatistics"
const OperationPublicUserGetLoginLog = "/api.public.user.v1.PublicUser/GetLoginLog"
const OperationPublicUserGetOAuthMethods = "/api.public.user.v1.PublicUser/GetOAuthMethods"
const OperationPublicUserGetSubscribeLog = "/api.public.user.v1.PublicUser/GetSubscribeLog"
const OperationPublicUserGetUserTrafficStats = "/api.public.user.v1.PublicUser/GetUserTrafficStats"
const OperationPublicUserPreUnsubscribe = "/api.public.user.v1.PublicUser/PreUnsubscribe"
const OperationPublicUserQueryUserAffiliate = "/api.public.user.v1.PublicUser/QueryUserAffiliate"
const OperationPublicUserQueryUserAffiliateList = "/api.public.user.v1.PublicUser/QueryUserAffiliateList"
const OperationPublicUserQueryUserBalanceLog = "/api.public.user.v1.PublicUser/QueryUserBalanceLog"
const OperationPublicUserQueryUserCommissionLog = "/api.public.user.v1.PublicUser/QueryUserCommissionLog"
const OperationPublicUserQueryUserInfo = "/api.public.user.v1.PublicUser/QueryUserInfo"
const OperationPublicUserQueryUserSubscribe = "/api.public.user.v1.PublicUser/QueryUserSubscribe"
const OperationPublicUserQueryWithdrawalLog = "/api.public.user.v1.PublicUser/QueryWithdrawalLog"
const OperationPublicUserResetUserSubscribeToken = "/api.public.user.v1.PublicUser/ResetUserSubscribeToken"
const OperationPublicUserUnbindDevice = "/api.public.user.v1.PublicUser/UnbindDevice"
const OperationPublicUserUnbindOAuth = "/api.public.user.v1.PublicUser/UnbindOAuth"
const OperationPublicUserUnbindTelegram = "/api.public.user.v1.PublicUser/UnbindTelegram"
const OperationPublicUserUnsubscribe = "/api.public.user.v1.PublicUser/Unsubscribe"
const OperationPublicUserUpdateBindEmail = "/api.public.user.v1.PublicUser/UpdateBindEmail"
const OperationPublicUserUpdateBindMobile = "/api.public.user.v1.PublicUser/UpdateBindMobile"
const OperationPublicUserUpdateUserNotify = "/api.public.user.v1.PublicUser/UpdateUserNotify"
const OperationPublicUserUpdateUserPassword = "/api.public.user.v1.PublicUser/UpdateUserPassword"
const OperationPublicUserUpdateUserRules = "/api.public.user.v1.PublicUser/UpdateUserRules"
const OperationPublicUserUpdateUserSubscribeNote = "/api.public.user.v1.PublicUser/UpdateUserSubscribeNote"
const OperationPublicUserVerifyEmail = "/api.public.user.v1.PublicUser/VerifyEmail"

type PublicUserHTTPServer interface {
	// BindOAuth BindOAuth 绑定OAuth
	BindOAuth(context.Context, *BindOAuthRequest) (*BindOAuthReply, error)
	// BindOAuthCallback BindOAuthCallback OAuth回调
	BindOAuthCallback(context.Context, *BindOAuthCallbackRequest) (*emptypb.Empty, error)
	// BindTelegram BindTelegram 绑定Telegram
	BindTelegram(context.Context, *emptypb.Empty) (*BindTelegramReply, error)
	// CommissionWithdraw CommissionWithdraw 佣金提现
	CommissionWithdraw(context.Context, *CommissionWithdrawRequest) (*WithdrawalLog, error)
	// DeleteCurrentUserAccount DeleteCurrentUserAccount 删除当前用户账号
	DeleteCurrentUserAccount(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// DeviceWSConnect DeviceWSConnect 设备WebSocket连接
	DeviceWSConnect(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// GetDeviceList GetDeviceList 获取设备列表
	GetDeviceList(context.Context, *emptypb.Empty) (*GetDeviceListReply, error)
	// GetDeviceOnlineStatistics GetDeviceOnlineStatistics 获取设备在线统计
	GetDeviceOnlineStatistics(context.Context, *emptypb.Empty) (*GetDeviceOnlineStatisticsReply, error)
	// GetLoginLog GetLoginLog 获取登录日志
	GetLoginLog(context.Context, *GetLoginLogRequest) (*GetLoginLogReply, error)
	// GetOAuthMethods GetOAuthMethods 获取OAuth方法
	GetOAuthMethods(context.Context, *emptypb.Empty) (*GetOAuthMethodsReply, error)
	// GetSubscribeLog GetSubscribeLog 获取订阅日志
	GetSubscribeLog(context.Context, *GetSubscribeLogRequest) (*GetSubscribeLogReply, error)
	// GetUserTrafficStats GetUserTrafficStats 获取用户流量统计
	GetUserTrafficStats(context.Context, *GetUserTrafficStatsRequest) (*GetUserTrafficStatsReply, error)
	// PreUnsubscribe PreUnsubscribe 预退订
	PreUnsubscribe(context.Context, *PreUnsubscribeRequest) (*PreUnsubscribeReply, error)
	// QueryUserAffiliate QueryUserAffiliate 查询用户推荐数量
	QueryUserAffiliate(context.Context, *emptypb.Empty) (*QueryUserAffiliateCountReply, error)
	// QueryUserAffiliateList QueryUserAffiliateList 查询用户推荐列表
	QueryUserAffiliateList(context.Context, *QueryUserAffiliateListRequest) (*QueryUserAffiliateListReply, error)
	// QueryUserBalanceLog QueryUserBalanceLog 查询用户余额日志
	QueryUserBalanceLog(context.Context, *emptypb.Empty) (*QueryUserBalanceLogReply, error)
	// QueryUserCommissionLog QueryUserCommissionLog 查询用户佣金日志
	QueryUserCommissionLog(context.Context, *QueryUserCommissionLogRequest) (*QueryUserCommissionLogReply, error)
	// QueryUserInfo QueryUserInfo 查询用户信息
	QueryUserInfo(context.Context, *emptypb.Empty) (*User, error)
	// QueryUserSubscribe QueryUserSubscribe 查询用户订阅
	QueryUserSubscribe(context.Context, *emptypb.Empty) (*QueryUserSubscribeReply, error)
	// QueryWithdrawalLog QueryWithdrawalLog 查询提现日志
	QueryWithdrawalLog(context.Context, *QueryWithdrawalLogRequest) (*QueryWithdrawalLogReply, error)
	// ResetUserSubscribeToken ResetUserSubscribeToken 重置订阅令牌
	ResetUserSubscribeToken(context.Context, *ResetUserSubscribeTokenRequest) (*emptypb.Empty, error)
	// UnbindDevice UnbindDevice 解绑设备
	UnbindDevice(context.Context, *UnbindDeviceRequest) (*emptypb.Empty, error)
	// UnbindOAuth UnbindOAuth 解绑OAuth
	UnbindOAuth(context.Context, *UnbindOAuthRequest) (*emptypb.Empty, error)
	// UnbindTelegram UnbindTelegram 解绑Telegram
	UnbindTelegram(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Unsubscribe Unsubscribe 退订
	Unsubscribe(context.Context, *UnsubscribeRequest) (*emptypb.Empty, error)
	// UpdateBindEmail UpdateBindEmail 更新绑定邮箱
	UpdateBindEmail(context.Context, *UpdateBindEmailRequest) (*emptypb.Empty, error)
	// UpdateBindMobile UpdateBindMobile 更新绑定手机
	UpdateBindMobile(context.Context, *UpdateBindMobileRequest) (*emptypb.Empty, error)
	// UpdateUserNotify UpdateUserNotify 更新通知设置
	UpdateUserNotify(context.Context, *UpdateUserNotifyRequest) (*emptypb.Empty, error)
	// UpdateUserPassword UpdateUserPassword 更新密码
	UpdateUserPassword(context.Context, *UpdateUserPasswordRequest) (*emptypb.Empty, error)
	// UpdateUserRules UpdateUserRules 更新用户规则
	UpdateUserRules(context.Context, *UpdateUserRulesRequest) (*emptypb.Empty, error)
	// UpdateUserSubscribeNote UpdateUserSubscribeNote 更新用户订阅备注
	UpdateUserSubscribeNote(context.Context, *UpdateUserSubscribeNoteRequest) (*emptypb.Empty, error)
	// VerifyEmail VerifyEmail 验证邮箱
	VerifyEmail(context.Context, *VerifyEmailRequest) (*emptypb.Empty, error)
}

func RegisterPublicUserHTTPServer(s *http.Server, srv PublicUserHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/public/user/info", _PublicUser_QueryUserInfo0_HTTP_Handler(srv))
	r.GET("/v1/public/user/login_log", _PublicUser_GetLoginLog0_HTTP_Handler(srv))
	r.GET("/v1/public/user/balance_log", _PublicUser_QueryUserBalanceLog0_HTTP_Handler(srv))
	r.GET("/v1/public/user/commission_log", _PublicUser_QueryUserCommissionLog0_HTTP_Handler(srv))
	r.GET("/v1/public/user/affiliate/count", _PublicUser_QueryUserAffiliate0_HTTP_Handler(srv))
	r.GET("/v1/public/user/affiliate/list", _PublicUser_QueryUserAffiliateList0_HTTP_Handler(srv))
	r.GET("/v1/public/user/oauth_methods", _PublicUser_GetOAuthMethods0_HTTP_Handler(srv))
	r.GET("/v1/public/user/subscribe", _PublicUser_QueryUserSubscribe0_HTTP_Handler(srv))
	r.GET("/v1/public/user/subscribe_log", _PublicUser_GetSubscribeLog0_HTTP_Handler(srv))
	r.PUT("/v1/public/user/subscribe_token", _PublicUser_ResetUserSubscribeToken0_HTTP_Handler(srv))
	r.POST("/v1/public/user/unsubscribe/pre", _PublicUser_PreUnsubscribe0_HTTP_Handler(srv))
	r.POST("/v1/public/user/unsubscribe", _PublicUser_Unsubscribe0_HTTP_Handler(srv))
	r.PUT("/v1/public/user/notify", _PublicUser_UpdateUserNotify0_HTTP_Handler(srv))
	r.PUT("/v1/public/user/password", _PublicUser_UpdateUserPassword0_HTTP_Handler(srv))
	r.GET("/v1/public/user/bind_telegram", _PublicUser_BindTelegram0_HTTP_Handler(srv))
	r.POST("/v1/public/user/unbind_telegram", _PublicUser_UnbindTelegram0_HTTP_Handler(srv))
	r.POST("/v1/public/user/bind_oauth", _PublicUser_BindOAuth0_HTTP_Handler(srv))
	r.POST("/v1/public/user/bind_oauth/callback", _PublicUser_BindOAuthCallback0_HTTP_Handler(srv))
	r.POST("/v1/public/user/unbind_oauth", _PublicUser_UnbindOAuth0_HTTP_Handler(srv))
	r.POST("/v1/public/user/verify_email", _PublicUser_VerifyEmail0_HTTP_Handler(srv))
	r.PUT("/v1/public/user/bind_mobile", _PublicUser_UpdateBindMobile0_HTTP_Handler(srv))
	r.PUT("/v1/public/user/bind_email", _PublicUser_UpdateBindEmail0_HTTP_Handler(srv))
	r.GET("/v1/public/user/devices", _PublicUser_GetDeviceList0_HTTP_Handler(srv))
	r.PUT("/v1/public/user/unbind_device", _PublicUser_UnbindDevice0_HTTP_Handler(srv))
	r.GET("/v1/public/user/device_online_statistics", _PublicUser_GetDeviceOnlineStatistics0_HTTP_Handler(srv))
	r.GET("/v1/public/user/device_ws_connect", _PublicUser_DeviceWSConnect0_HTTP_Handler(srv))
	r.POST("/v1/public/user/commission_withdraw", _PublicUser_CommissionWithdraw0_HTTP_Handler(srv))
	r.GET("/v1/public/user/withdrawal_log", _PublicUser_QueryWithdrawalLog0_HTTP_Handler(srv))
	r.PUT("/v1/public/user/subscribe_note", _PublicUser_UpdateUserSubscribeNote0_HTTP_Handler(srv))
	r.PUT("/v1/public/user/rules", _PublicUser_UpdateUserRules0_HTTP_Handler(srv))
	r.DELETE("/v1/public/user/current_user_account", _PublicUser_DeleteCurrentUserAccount0_HTTP_Handler(srv))
	r.GET("/v1/public/user/traffic_stats", _PublicUser_GetUserTrafficStats0_HTTP_Handler(srv))
}

func _PublicUser_QueryUserInfo0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserQueryUserInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryUserInfo(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_GetLoginLog0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLoginLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserGetLoginLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLoginLog(ctx, req.(*GetLoginLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLoginLogReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_QueryUserBalanceLog0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserQueryUserBalanceLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryUserBalanceLog(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryUserBalanceLogReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_QueryUserCommissionLog0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryUserCommissionLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserQueryUserCommissionLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryUserCommissionLog(ctx, req.(*QueryUserCommissionLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryUserCommissionLogReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_QueryUserAffiliate0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserQueryUserAffiliate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryUserAffiliate(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryUserAffiliateCountReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_QueryUserAffiliateList0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryUserAffiliateListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserQueryUserAffiliateList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryUserAffiliateList(ctx, req.(*QueryUserAffiliateListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryUserAffiliateListReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_GetOAuthMethods0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserGetOAuthMethods)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOAuthMethods(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOAuthMethodsReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_QueryUserSubscribe0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserQueryUserSubscribe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryUserSubscribe(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryUserSubscribeReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_GetSubscribeLog0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSubscribeLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserGetSubscribeLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSubscribeLog(ctx, req.(*GetSubscribeLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSubscribeLogReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_ResetUserSubscribeToken0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResetUserSubscribeTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserResetUserSubscribeToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResetUserSubscribeToken(ctx, req.(*ResetUserSubscribeTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_PreUnsubscribe0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreUnsubscribeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserPreUnsubscribe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreUnsubscribe(ctx, req.(*PreUnsubscribeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreUnsubscribeReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_Unsubscribe0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnsubscribeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUnsubscribe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Unsubscribe(ctx, req.(*UnsubscribeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_UpdateUserNotify0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserNotifyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUpdateUserNotify)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserNotify(ctx, req.(*UpdateUserNotifyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_UpdateUserPassword0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserPasswordRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUpdateUserPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserPassword(ctx, req.(*UpdateUserPasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_BindTelegram0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserBindTelegram)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindTelegram(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BindTelegramReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_UnbindTelegram0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUnbindTelegram)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnbindTelegram(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_BindOAuth0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindOAuthRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserBindOAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindOAuth(ctx, req.(*BindOAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BindOAuthReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_BindOAuthCallback0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindOAuthCallbackRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserBindOAuthCallback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindOAuthCallback(ctx, req.(*BindOAuthCallbackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_UnbindOAuth0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnbindOAuthRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUnbindOAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnbindOAuth(ctx, req.(*UnbindOAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_VerifyEmail0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerifyEmailRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserVerifyEmail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.VerifyEmail(ctx, req.(*VerifyEmailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_UpdateBindMobile0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateBindMobileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUpdateBindMobile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBindMobile(ctx, req.(*UpdateBindMobileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_UpdateBindEmail0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateBindEmailRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUpdateBindEmail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBindEmail(ctx, req.(*UpdateBindEmailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_GetDeviceList0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserGetDeviceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDeviceList(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDeviceListReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_UnbindDevice0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnbindDeviceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUnbindDevice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnbindDevice(ctx, req.(*UnbindDeviceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_GetDeviceOnlineStatistics0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserGetDeviceOnlineStatistics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDeviceOnlineStatistics(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDeviceOnlineStatisticsReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_DeviceWSConnect0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserDeviceWSConnect)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeviceWSConnect(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_CommissionWithdraw0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CommissionWithdrawRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserCommissionWithdraw)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CommissionWithdraw(ctx, req.(*CommissionWithdrawRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WithdrawalLog)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_QueryWithdrawalLog0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryWithdrawalLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserQueryWithdrawalLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryWithdrawalLog(ctx, req.(*QueryWithdrawalLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryWithdrawalLogReply)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_UpdateUserSubscribeNote0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserSubscribeNoteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUpdateUserSubscribeNote)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserSubscribeNote(ctx, req.(*UpdateUserSubscribeNoteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_UpdateUserRules0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserRulesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserUpdateUserRules)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserRules(ctx, req.(*UpdateUserRulesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_DeleteCurrentUserAccount0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserDeleteCurrentUserAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCurrentUserAccount(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PublicUser_GetUserTrafficStats0_HTTP_Handler(srv PublicUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserTrafficStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicUserGetUserTrafficStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserTrafficStats(ctx, req.(*GetUserTrafficStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserTrafficStatsReply)
		return ctx.Result(200, reply)
	}
}

type PublicUserHTTPClient interface {
	// BindOAuth BindOAuth 绑定OAuth
	BindOAuth(ctx context.Context, req *BindOAuthRequest, opts ...http.CallOption) (rsp *BindOAuthReply, err error)
	// BindOAuthCallback BindOAuthCallback OAuth回调
	BindOAuthCallback(ctx context.Context, req *BindOAuthCallbackRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// BindTelegram BindTelegram 绑定Telegram
	BindTelegram(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *BindTelegramReply, err error)
	// CommissionWithdraw CommissionWithdraw 佣金提现
	CommissionWithdraw(ctx context.Context, req *CommissionWithdrawRequest, opts ...http.CallOption) (rsp *WithdrawalLog, err error)
	// DeleteCurrentUserAccount DeleteCurrentUserAccount 删除当前用户账号
	DeleteCurrentUserAccount(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// DeviceWSConnect DeviceWSConnect 设备WebSocket连接
	DeviceWSConnect(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetDeviceList GetDeviceList 获取设备列表
	GetDeviceList(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *GetDeviceListReply, err error)
	// GetDeviceOnlineStatistics GetDeviceOnlineStatistics 获取设备在线统计
	GetDeviceOnlineStatistics(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *GetDeviceOnlineStatisticsReply, err error)
	// GetLoginLog GetLoginLog 获取登录日志
	GetLoginLog(ctx context.Context, req *GetLoginLogRequest, opts ...http.CallOption) (rsp *GetLoginLogReply, err error)
	// GetOAuthMethods GetOAuthMethods 获取OAuth方法
	GetOAuthMethods(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *GetOAuthMethodsReply, err error)
	// GetSubscribeLog GetSubscribeLog 获取订阅日志
	GetSubscribeLog(ctx context.Context, req *GetSubscribeLogRequest, opts ...http.CallOption) (rsp *GetSubscribeLogReply, err error)
	// GetUserTrafficStats GetUserTrafficStats 获取用户流量统计
	GetUserTrafficStats(ctx context.Context, req *GetUserTrafficStatsRequest, opts ...http.CallOption) (rsp *GetUserTrafficStatsReply, err error)
	// PreUnsubscribe PreUnsubscribe 预退订
	PreUnsubscribe(ctx context.Context, req *PreUnsubscribeRequest, opts ...http.CallOption) (rsp *PreUnsubscribeReply, err error)
	// QueryUserAffiliate QueryUserAffiliate 查询用户推荐数量
	QueryUserAffiliate(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *QueryUserAffiliateCountReply, err error)
	// QueryUserAffiliateList QueryUserAffiliateList 查询用户推荐列表
	QueryUserAffiliateList(ctx context.Context, req *QueryUserAffiliateListRequest, opts ...http.CallOption) (rsp *QueryUserAffiliateListReply, err error)
	// QueryUserBalanceLog QueryUserBalanceLog 查询用户余额日志
	QueryUserBalanceLog(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *QueryUserBalanceLogReply, err error)
	// QueryUserCommissionLog QueryUserCommissionLog 查询用户佣金日志
	QueryUserCommissionLog(ctx context.Context, req *QueryUserCommissionLogRequest, opts ...http.CallOption) (rsp *QueryUserCommissionLogReply, err error)
	// QueryUserInfo QueryUserInfo 查询用户信息
	QueryUserInfo(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *User, err error)
	// QueryUserSubscribe QueryUserSubscribe 查询用户订阅
	QueryUserSubscribe(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *QueryUserSubscribeReply, err error)
	// QueryWithdrawalLog QueryWithdrawalLog 查询提现日志
	QueryWithdrawalLog(ctx context.Context, req *QueryWithdrawalLogRequest, opts ...http.CallOption) (rsp *QueryWithdrawalLogReply, err error)
	// ResetUserSubscribeToken ResetUserSubscribeToken 重置订阅令牌
	ResetUserSubscribeToken(ctx context.Context, req *ResetUserSubscribeTokenRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UnbindDevice UnbindDevice 解绑设备
	UnbindDevice(ctx context.Context, req *UnbindDeviceRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UnbindOAuth UnbindOAuth 解绑OAuth
	UnbindOAuth(ctx context.Context, req *UnbindOAuthRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UnbindTelegram UnbindTelegram 解绑Telegram
	UnbindTelegram(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// Unsubscribe Unsubscribe 退订
	Unsubscribe(ctx context.Context, req *UnsubscribeRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UpdateBindEmail UpdateBindEmail 更新绑定邮箱
	UpdateBindEmail(ctx context.Context, req *UpdateBindEmailRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UpdateBindMobile UpdateBindMobile 更新绑定手机
	UpdateBindMobile(ctx context.Context, req *UpdateBindMobileRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UpdateUserNotify UpdateUserNotify 更新通知设置
	UpdateUserNotify(ctx context.Context, req *UpdateUserNotifyRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UpdateUserPassword UpdateUserPassword 更新密码
	UpdateUserPassword(ctx context.Context, req *UpdateUserPasswordRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UpdateUserRules UpdateUserRules 更新用户规则
	UpdateUserRules(ctx context.Context, req *UpdateUserRulesRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UpdateUserSubscribeNote UpdateUserSubscribeNote 更新用户订阅备注
	UpdateUserSubscribeNote(ctx context.Context, req *UpdateUserSubscribeNoteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// VerifyEmail VerifyEmail 验证邮箱
	VerifyEmail(ctx context.Context, req *VerifyEmailRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type PublicUserHTTPClientImpl struct {
	cc *http.Client
}

func NewPublicUserHTTPClient(client *http.Client) PublicUserHTTPClient {
	return &PublicUserHTTPClientImpl{client}
}

// BindOAuth BindOAuth 绑定OAuth
func (c *PublicUserHTTPClientImpl) BindOAuth(ctx context.Context, in *BindOAuthRequest, opts ...http.CallOption) (*BindOAuthReply, error) {
	var out BindOAuthReply
	pattern := "/v1/public/user/bind_oauth"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserBindOAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BindOAuthCallback BindOAuthCallback OAuth回调
func (c *PublicUserHTTPClientImpl) BindOAuthCallback(ctx context.Context, in *BindOAuthCallbackRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/bind_oauth/callback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserBindOAuthCallback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BindTelegram BindTelegram 绑定Telegram
func (c *PublicUserHTTPClientImpl) BindTelegram(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*BindTelegramReply, error) {
	var out BindTelegramReply
	pattern := "/v1/public/user/bind_telegram"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserBindTelegram))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CommissionWithdraw CommissionWithdraw 佣金提现
func (c *PublicUserHTTPClientImpl) CommissionWithdraw(ctx context.Context, in *CommissionWithdrawRequest, opts ...http.CallOption) (*WithdrawalLog, error) {
	var out WithdrawalLog
	pattern := "/v1/public/user/commission_withdraw"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserCommissionWithdraw))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteCurrentUserAccount DeleteCurrentUserAccount 删除当前用户账号
func (c *PublicUserHTTPClientImpl) DeleteCurrentUserAccount(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/current_user_account"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserDeleteCurrentUserAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeviceWSConnect DeviceWSConnect 设备WebSocket连接
func (c *PublicUserHTTPClientImpl) DeviceWSConnect(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/device_ws_connect"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserDeviceWSConnect))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDeviceList GetDeviceList 获取设备列表
func (c *PublicUserHTTPClientImpl) GetDeviceList(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*GetDeviceListReply, error) {
	var out GetDeviceListReply
	pattern := "/v1/public/user/devices"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserGetDeviceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDeviceOnlineStatistics GetDeviceOnlineStatistics 获取设备在线统计
func (c *PublicUserHTTPClientImpl) GetDeviceOnlineStatistics(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*GetDeviceOnlineStatisticsReply, error) {
	var out GetDeviceOnlineStatisticsReply
	pattern := "/v1/public/user/device_online_statistics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserGetDeviceOnlineStatistics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLoginLog GetLoginLog 获取登录日志
func (c *PublicUserHTTPClientImpl) GetLoginLog(ctx context.Context, in *GetLoginLogRequest, opts ...http.CallOption) (*GetLoginLogReply, error) {
	var out GetLoginLogReply
	pattern := "/v1/public/user/login_log"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserGetLoginLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetOAuthMethods GetOAuthMethods 获取OAuth方法
func (c *PublicUserHTTPClientImpl) GetOAuthMethods(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*GetOAuthMethodsReply, error) {
	var out GetOAuthMethodsReply
	pattern := "/v1/public/user/oauth_methods"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserGetOAuthMethods))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSubscribeLog GetSubscribeLog 获取订阅日志
func (c *PublicUserHTTPClientImpl) GetSubscribeLog(ctx context.Context, in *GetSubscribeLogRequest, opts ...http.CallOption) (*GetSubscribeLogReply, error) {
	var out GetSubscribeLogReply
	pattern := "/v1/public/user/subscribe_log"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserGetSubscribeLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserTrafficStats GetUserTrafficStats 获取用户流量统计
func (c *PublicUserHTTPClientImpl) GetUserTrafficStats(ctx context.Context, in *GetUserTrafficStatsRequest, opts ...http.CallOption) (*GetUserTrafficStatsReply, error) {
	var out GetUserTrafficStatsReply
	pattern := "/v1/public/user/traffic_stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserGetUserTrafficStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PreUnsubscribe PreUnsubscribe 预退订
func (c *PublicUserHTTPClientImpl) PreUnsubscribe(ctx context.Context, in *PreUnsubscribeRequest, opts ...http.CallOption) (*PreUnsubscribeReply, error) {
	var out PreUnsubscribeReply
	pattern := "/v1/public/user/unsubscribe/pre"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserPreUnsubscribe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryUserAffiliate QueryUserAffiliate 查询用户推荐数量
func (c *PublicUserHTTPClientImpl) QueryUserAffiliate(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*QueryUserAffiliateCountReply, error) {
	var out QueryUserAffiliateCountReply
	pattern := "/v1/public/user/affiliate/count"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserQueryUserAffiliate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryUserAffiliateList QueryUserAffiliateList 查询用户推荐列表
func (c *PublicUserHTTPClientImpl) QueryUserAffiliateList(ctx context.Context, in *QueryUserAffiliateListRequest, opts ...http.CallOption) (*QueryUserAffiliateListReply, error) {
	var out QueryUserAffiliateListReply
	pattern := "/v1/public/user/affiliate/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserQueryUserAffiliateList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryUserBalanceLog QueryUserBalanceLog 查询用户余额日志
func (c *PublicUserHTTPClientImpl) QueryUserBalanceLog(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*QueryUserBalanceLogReply, error) {
	var out QueryUserBalanceLogReply
	pattern := "/v1/public/user/balance_log"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserQueryUserBalanceLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryUserCommissionLog QueryUserCommissionLog 查询用户佣金日志
func (c *PublicUserHTTPClientImpl) QueryUserCommissionLog(ctx context.Context, in *QueryUserCommissionLogRequest, opts ...http.CallOption) (*QueryUserCommissionLogReply, error) {
	var out QueryUserCommissionLogReply
	pattern := "/v1/public/user/commission_log"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserQueryUserCommissionLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryUserInfo QueryUserInfo 查询用户信息
func (c *PublicUserHTTPClientImpl) QueryUserInfo(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/public/user/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserQueryUserInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryUserSubscribe QueryUserSubscribe 查询用户订阅
func (c *PublicUserHTTPClientImpl) QueryUserSubscribe(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*QueryUserSubscribeReply, error) {
	var out QueryUserSubscribeReply
	pattern := "/v1/public/user/subscribe"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserQueryUserSubscribe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryWithdrawalLog QueryWithdrawalLog 查询提现日志
func (c *PublicUserHTTPClientImpl) QueryWithdrawalLog(ctx context.Context, in *QueryWithdrawalLogRequest, opts ...http.CallOption) (*QueryWithdrawalLogReply, error) {
	var out QueryWithdrawalLogReply
	pattern := "/v1/public/user/withdrawal_log"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserQueryWithdrawalLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResetUserSubscribeToken ResetUserSubscribeToken 重置订阅令牌
func (c *PublicUserHTTPClientImpl) ResetUserSubscribeToken(ctx context.Context, in *ResetUserSubscribeTokenRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/subscribe_token"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserResetUserSubscribeToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UnbindDevice UnbindDevice 解绑设备
func (c *PublicUserHTTPClientImpl) UnbindDevice(ctx context.Context, in *UnbindDeviceRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/unbind_device"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserUnbindDevice))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UnbindOAuth UnbindOAuth 解绑OAuth
func (c *PublicUserHTTPClientImpl) UnbindOAuth(ctx context.Context, in *UnbindOAuthRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/unbind_oauth"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserUnbindOAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UnbindTelegram UnbindTelegram 解绑Telegram
func (c *PublicUserHTTPClientImpl) UnbindTelegram(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/unbind_telegram"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserUnbindTelegram))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Unsubscribe Unsubscribe 退订
func (c *PublicUserHTTPClientImpl) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/unsubscribe"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserUnsubscribe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateBindEmail UpdateBindEmail 更新绑定邮箱
func (c *PublicUserHTTPClientImpl) UpdateBindEmail(ctx context.Context, in *UpdateBindEmailRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/bind_email"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserUpdateBindEmail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateBindMobile UpdateBindMobile 更新绑定手机
func (c *PublicUserHTTPClientImpl) UpdateBindMobile(ctx context.Context, in *UpdateBindMobileRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/bind_mobile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserUpdateBindMobile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateUserNotify UpdateUserNotify 更新通知设置
func (c *PublicUserHTTPClientImpl) UpdateUserNotify(ctx context.Context, in *UpdateUserNotifyRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/notify"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserUpdateUserNotify))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateUserPassword UpdateUserPassword 更新密码
func (c *PublicUserHTTPClientImpl) UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/password"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublicUserUpdateUserPassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateUserRules UpdateUserRules 更新用户规则
func (c *PublicUserHTTPClientImpl) UpdateUserRules(ctx context.Context, in *UpdateUserRulesRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/rules"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserUpdateUserRules))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateUserSubscribeNote UpdateUserSubscribeNote 更新用户订阅备注
func (c *PublicUserHTTPClientImpl) UpdateUserSubscribeNote(ctx context.Context, in *UpdateUserSubscribeNoteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/subscribe_note"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserUpdateUserSubscribeNote))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// VerifyEmail VerifyEmail 验证邮箱
func (c *PublicUserHTTPClientImpl) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/public/user/verify_email"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicUserVerifyEmail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
