// Code generated by ent, DO NOT EDIT.

package proxyorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/npanel-dev/NPanel-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldID, id))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldParentID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldUserID, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldOrderNo, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldType, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int32) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldQuantity, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldPrice, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldAmount, v))
}

// GiftAmount applies equality check predicate on the "gift_amount" field. It's identical to GiftAmountEQ.
func GiftAmount(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldGiftAmount, v))
}

// Discount applies equality check predicate on the "discount" field. It's identical to DiscountEQ.
func Discount(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldDiscount, v))
}

// Coupon applies equality check predicate on the "coupon" field. It's identical to CouponEQ.
func Coupon(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldCoupon, v))
}

// CouponDiscount applies equality check predicate on the "coupon_discount" field. It's identical to CouponDiscountEQ.
func CouponDiscount(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldCouponDiscount, v))
}

// Commission applies equality check predicate on the "commission" field. It's identical to CommissionEQ.
func Commission(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldCommission, v))
}

// PaymentID applies equality check predicate on the "payment_id" field. It's identical to PaymentIDEQ.
func PaymentID(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldPaymentID, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldMethod, v))
}

// FeeAmount applies equality check predicate on the "fee_amount" field. It's identical to FeeAmountEQ.
func FeeAmount(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldFeeAmount, v))
}

// TradeNo applies equality check predicate on the "trade_no" field. It's identical to TradeNoEQ.
func TradeNo(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldTradeNo, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldStatus, v))
}

// SubscribeID applies equality check predicate on the "subscribe_id" field. It's identical to SubscribeIDEQ.
func SubscribeID(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldSubscribeID, v))
}

// PriceOptionID applies equality check predicate on the "price_option_id" field. It's identical to PriceOptionIDEQ.
func PriceOptionID(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldPriceOptionID, v))
}

// PriceOptionName applies equality check predicate on the "price_option_name" field. It's identical to PriceOptionNameEQ.
func PriceOptionName(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldPriceOptionName, v))
}

// DurationUnit applies equality check predicate on the "duration_unit" field. It's identical to DurationUnitEQ.
func DurationUnit(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldDurationUnit, v))
}

// DurationValue applies equality check predicate on the "duration_value" field. It's identical to DurationValueEQ.
func DurationValue(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldDurationValue, v))
}

// OptionPrice applies equality check predicate on the "option_price" field. It's identical to OptionPriceEQ.
func OptionPrice(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldOptionPrice, v))
}

// SubscribeToken applies equality check predicate on the "subscribe_token" field. It's identical to SubscribeTokenEQ.
func SubscribeToken(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldSubscribeToken, v))
}

// IsNew applies equality check predicate on the "is_new" field. It's identical to IsNewEQ.
func IsNew(v bool) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldIsNew, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldParentID, v))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotNull(FieldParentID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldUserID, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldType, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int32) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int32) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int32) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int32) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int32) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int32) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int32) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int32) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldQuantity, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldPrice, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldAmount, v))
}

// GiftAmountEQ applies the EQ predicate on the "gift_amount" field.
func GiftAmountEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldGiftAmount, v))
}

// GiftAmountNEQ applies the NEQ predicate on the "gift_amount" field.
func GiftAmountNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldGiftAmount, v))
}

// GiftAmountIn applies the In predicate on the "gift_amount" field.
func GiftAmountIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldGiftAmount, vs...))
}

// GiftAmountNotIn applies the NotIn predicate on the "gift_amount" field.
func GiftAmountNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldGiftAmount, vs...))
}

// GiftAmountGT applies the GT predicate on the "gift_amount" field.
func GiftAmountGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldGiftAmount, v))
}

// GiftAmountGTE applies the GTE predicate on the "gift_amount" field.
func GiftAmountGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldGiftAmount, v))
}

// GiftAmountLT applies the LT predicate on the "gift_amount" field.
func GiftAmountLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldGiftAmount, v))
}

// GiftAmountLTE applies the LTE predicate on the "gift_amount" field.
func GiftAmountLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldGiftAmount, v))
}

// DiscountEQ applies the EQ predicate on the "discount" field.
func DiscountEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldDiscount, v))
}

// DiscountNEQ applies the NEQ predicate on the "discount" field.
func DiscountNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldDiscount, v))
}

// DiscountIn applies the In predicate on the "discount" field.
func DiscountIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldDiscount, vs...))
}

// DiscountNotIn applies the NotIn predicate on the "discount" field.
func DiscountNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldDiscount, vs...))
}

// DiscountGT applies the GT predicate on the "discount" field.
func DiscountGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldDiscount, v))
}

// DiscountGTE applies the GTE predicate on the "discount" field.
func DiscountGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldDiscount, v))
}

// DiscountLT applies the LT predicate on the "discount" field.
func DiscountLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldDiscount, v))
}

// DiscountLTE applies the LTE predicate on the "discount" field.
func DiscountLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldDiscount, v))
}

// CouponEQ applies the EQ predicate on the "coupon" field.
func CouponEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldCoupon, v))
}

// CouponNEQ applies the NEQ predicate on the "coupon" field.
func CouponNEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldCoupon, v))
}

// CouponIn applies the In predicate on the "coupon" field.
func CouponIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldCoupon, vs...))
}

// CouponNotIn applies the NotIn predicate on the "coupon" field.
func CouponNotIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldCoupon, vs...))
}

// CouponGT applies the GT predicate on the "coupon" field.
func CouponGT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldCoupon, v))
}

// CouponGTE applies the GTE predicate on the "coupon" field.
func CouponGTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldCoupon, v))
}

// CouponLT applies the LT predicate on the "coupon" field.
func CouponLT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldCoupon, v))
}

// CouponLTE applies the LTE predicate on the "coupon" field.
func CouponLTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldCoupon, v))
}

// CouponContains applies the Contains predicate on the "coupon" field.
func CouponContains(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContains(FieldCoupon, v))
}

// CouponHasPrefix applies the HasPrefix predicate on the "coupon" field.
func CouponHasPrefix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasPrefix(FieldCoupon, v))
}

// CouponHasSuffix applies the HasSuffix predicate on the "coupon" field.
func CouponHasSuffix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasSuffix(FieldCoupon, v))
}

// CouponIsNil applies the IsNil predicate on the "coupon" field.
func CouponIsNil() predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIsNull(FieldCoupon))
}

// CouponNotNil applies the NotNil predicate on the "coupon" field.
func CouponNotNil() predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotNull(FieldCoupon))
}

// CouponEqualFold applies the EqualFold predicate on the "coupon" field.
func CouponEqualFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEqualFold(FieldCoupon, v))
}

// CouponContainsFold applies the ContainsFold predicate on the "coupon" field.
func CouponContainsFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContainsFold(FieldCoupon, v))
}

// CouponDiscountEQ applies the EQ predicate on the "coupon_discount" field.
func CouponDiscountEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldCouponDiscount, v))
}

// CouponDiscountNEQ applies the NEQ predicate on the "coupon_discount" field.
func CouponDiscountNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldCouponDiscount, v))
}

// CouponDiscountIn applies the In predicate on the "coupon_discount" field.
func CouponDiscountIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldCouponDiscount, vs...))
}

// CouponDiscountNotIn applies the NotIn predicate on the "coupon_discount" field.
func CouponDiscountNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldCouponDiscount, vs...))
}

// CouponDiscountGT applies the GT predicate on the "coupon_discount" field.
func CouponDiscountGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldCouponDiscount, v))
}

// CouponDiscountGTE applies the GTE predicate on the "coupon_discount" field.
func CouponDiscountGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldCouponDiscount, v))
}

// CouponDiscountLT applies the LT predicate on the "coupon_discount" field.
func CouponDiscountLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldCouponDiscount, v))
}

// CouponDiscountLTE applies the LTE predicate on the "coupon_discount" field.
func CouponDiscountLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldCouponDiscount, v))
}

// CommissionEQ applies the EQ predicate on the "commission" field.
func CommissionEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldCommission, v))
}

// CommissionNEQ applies the NEQ predicate on the "commission" field.
func CommissionNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldCommission, v))
}

// CommissionIn applies the In predicate on the "commission" field.
func CommissionIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldCommission, vs...))
}

// CommissionNotIn applies the NotIn predicate on the "commission" field.
func CommissionNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldCommission, vs...))
}

// CommissionGT applies the GT predicate on the "commission" field.
func CommissionGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldCommission, v))
}

// CommissionGTE applies the GTE predicate on the "commission" field.
func CommissionGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldCommission, v))
}

// CommissionLT applies the LT predicate on the "commission" field.
func CommissionLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldCommission, v))
}

// CommissionLTE applies the LTE predicate on the "commission" field.
func CommissionLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldCommission, v))
}

// PaymentIDEQ applies the EQ predicate on the "payment_id" field.
func PaymentIDEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldPaymentID, v))
}

// PaymentIDNEQ applies the NEQ predicate on the "payment_id" field.
func PaymentIDNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldPaymentID, v))
}

// PaymentIDIn applies the In predicate on the "payment_id" field.
func PaymentIDIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldPaymentID, vs...))
}

// PaymentIDNotIn applies the NotIn predicate on the "payment_id" field.
func PaymentIDNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldPaymentID, vs...))
}

// PaymentIDGT applies the GT predicate on the "payment_id" field.
func PaymentIDGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldPaymentID, v))
}

// PaymentIDGTE applies the GTE predicate on the "payment_id" field.
func PaymentIDGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldPaymentID, v))
}

// PaymentIDLT applies the LT predicate on the "payment_id" field.
func PaymentIDLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldPaymentID, v))
}

// PaymentIDLTE applies the LTE predicate on the "payment_id" field.
func PaymentIDLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldPaymentID, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContainsFold(FieldMethod, v))
}

// FeeAmountEQ applies the EQ predicate on the "fee_amount" field.
func FeeAmountEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldFeeAmount, v))
}

// FeeAmountNEQ applies the NEQ predicate on the "fee_amount" field.
func FeeAmountNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldFeeAmount, v))
}

// FeeAmountIn applies the In predicate on the "fee_amount" field.
func FeeAmountIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldFeeAmount, vs...))
}

// FeeAmountNotIn applies the NotIn predicate on the "fee_amount" field.
func FeeAmountNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldFeeAmount, vs...))
}

// FeeAmountGT applies the GT predicate on the "fee_amount" field.
func FeeAmountGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldFeeAmount, v))
}

// FeeAmountGTE applies the GTE predicate on the "fee_amount" field.
func FeeAmountGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldFeeAmount, v))
}

// FeeAmountLT applies the LT predicate on the "fee_amount" field.
func FeeAmountLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldFeeAmount, v))
}

// FeeAmountLTE applies the LTE predicate on the "fee_amount" field.
func FeeAmountLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldFeeAmount, v))
}

// TradeNoEQ applies the EQ predicate on the "trade_no" field.
func TradeNoEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldTradeNo, v))
}

// TradeNoNEQ applies the NEQ predicate on the "trade_no" field.
func TradeNoNEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldTradeNo, v))
}

// TradeNoIn applies the In predicate on the "trade_no" field.
func TradeNoIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldTradeNo, vs...))
}

// TradeNoNotIn applies the NotIn predicate on the "trade_no" field.
func TradeNoNotIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldTradeNo, vs...))
}

// TradeNoGT applies the GT predicate on the "trade_no" field.
func TradeNoGT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldTradeNo, v))
}

// TradeNoGTE applies the GTE predicate on the "trade_no" field.
func TradeNoGTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldTradeNo, v))
}

// TradeNoLT applies the LT predicate on the "trade_no" field.
func TradeNoLT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldTradeNo, v))
}

// TradeNoLTE applies the LTE predicate on the "trade_no" field.
func TradeNoLTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldTradeNo, v))
}

// TradeNoContains applies the Contains predicate on the "trade_no" field.
func TradeNoContains(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContains(FieldTradeNo, v))
}

// TradeNoHasPrefix applies the HasPrefix predicate on the "trade_no" field.
func TradeNoHasPrefix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasPrefix(FieldTradeNo, v))
}

// TradeNoHasSuffix applies the HasSuffix predicate on the "trade_no" field.
func TradeNoHasSuffix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasSuffix(FieldTradeNo, v))
}

// TradeNoIsNil applies the IsNil predicate on the "trade_no" field.
func TradeNoIsNil() predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIsNull(FieldTradeNo))
}

// TradeNoNotNil applies the NotNil predicate on the "trade_no" field.
func TradeNoNotNil() predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotNull(FieldTradeNo))
}

// TradeNoEqualFold applies the EqualFold predicate on the "trade_no" field.
func TradeNoEqualFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEqualFold(FieldTradeNo, v))
}

// TradeNoContainsFold applies the ContainsFold predicate on the "trade_no" field.
func TradeNoContainsFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContainsFold(FieldTradeNo, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldStatus, v))
}

// SubscribeIDEQ applies the EQ predicate on the "subscribe_id" field.
func SubscribeIDEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldSubscribeID, v))
}

// SubscribeIDNEQ applies the NEQ predicate on the "subscribe_id" field.
func SubscribeIDNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldSubscribeID, v))
}

// SubscribeIDIn applies the In predicate on the "subscribe_id" field.
func SubscribeIDIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldSubscribeID, vs...))
}

// SubscribeIDNotIn applies the NotIn predicate on the "subscribe_id" field.
func SubscribeIDNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldSubscribeID, vs...))
}

// SubscribeIDGT applies the GT predicate on the "subscribe_id" field.
func SubscribeIDGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldSubscribeID, v))
}

// SubscribeIDGTE applies the GTE predicate on the "subscribe_id" field.
func SubscribeIDGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldSubscribeID, v))
}

// SubscribeIDLT applies the LT predicate on the "subscribe_id" field.
func SubscribeIDLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldSubscribeID, v))
}

// SubscribeIDLTE applies the LTE predicate on the "subscribe_id" field.
func SubscribeIDLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldSubscribeID, v))
}

// PriceOptionIDEQ applies the EQ predicate on the "price_option_id" field.
func PriceOptionIDEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldPriceOptionID, v))
}

// PriceOptionIDNEQ applies the NEQ predicate on the "price_option_id" field.
func PriceOptionIDNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldPriceOptionID, v))
}

// PriceOptionIDIn applies the In predicate on the "price_option_id" field.
func PriceOptionIDIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldPriceOptionID, vs...))
}

// PriceOptionIDNotIn applies the NotIn predicate on the "price_option_id" field.
func PriceOptionIDNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldPriceOptionID, vs...))
}

// PriceOptionIDGT applies the GT predicate on the "price_option_id" field.
func PriceOptionIDGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldPriceOptionID, v))
}

// PriceOptionIDGTE applies the GTE predicate on the "price_option_id" field.
func PriceOptionIDGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldPriceOptionID, v))
}

// PriceOptionIDLT applies the LT predicate on the "price_option_id" field.
func PriceOptionIDLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldPriceOptionID, v))
}

// PriceOptionIDLTE applies the LTE predicate on the "price_option_id" field.
func PriceOptionIDLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldPriceOptionID, v))
}

// PriceOptionNameEQ applies the EQ predicate on the "price_option_name" field.
func PriceOptionNameEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldPriceOptionName, v))
}

// PriceOptionNameNEQ applies the NEQ predicate on the "price_option_name" field.
func PriceOptionNameNEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldPriceOptionName, v))
}

// PriceOptionNameIn applies the In predicate on the "price_option_name" field.
func PriceOptionNameIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldPriceOptionName, vs...))
}

// PriceOptionNameNotIn applies the NotIn predicate on the "price_option_name" field.
func PriceOptionNameNotIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldPriceOptionName, vs...))
}

// PriceOptionNameGT applies the GT predicate on the "price_option_name" field.
func PriceOptionNameGT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldPriceOptionName, v))
}

// PriceOptionNameGTE applies the GTE predicate on the "price_option_name" field.
func PriceOptionNameGTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldPriceOptionName, v))
}

// PriceOptionNameLT applies the LT predicate on the "price_option_name" field.
func PriceOptionNameLT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldPriceOptionName, v))
}

// PriceOptionNameLTE applies the LTE predicate on the "price_option_name" field.
func PriceOptionNameLTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldPriceOptionName, v))
}

// PriceOptionNameContains applies the Contains predicate on the "price_option_name" field.
func PriceOptionNameContains(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContains(FieldPriceOptionName, v))
}

// PriceOptionNameHasPrefix applies the HasPrefix predicate on the "price_option_name" field.
func PriceOptionNameHasPrefix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasPrefix(FieldPriceOptionName, v))
}

// PriceOptionNameHasSuffix applies the HasSuffix predicate on the "price_option_name" field.
func PriceOptionNameHasSuffix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasSuffix(FieldPriceOptionName, v))
}

// PriceOptionNameEqualFold applies the EqualFold predicate on the "price_option_name" field.
func PriceOptionNameEqualFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEqualFold(FieldPriceOptionName, v))
}

// PriceOptionNameContainsFold applies the ContainsFold predicate on the "price_option_name" field.
func PriceOptionNameContainsFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContainsFold(FieldPriceOptionName, v))
}

// DurationUnitEQ applies the EQ predicate on the "duration_unit" field.
func DurationUnitEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldDurationUnit, v))
}

// DurationUnitNEQ applies the NEQ predicate on the "duration_unit" field.
func DurationUnitNEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldDurationUnit, v))
}

// DurationUnitIn applies the In predicate on the "duration_unit" field.
func DurationUnitIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldDurationUnit, vs...))
}

// DurationUnitNotIn applies the NotIn predicate on the "duration_unit" field.
func DurationUnitNotIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldDurationUnit, vs...))
}

// DurationUnitGT applies the GT predicate on the "duration_unit" field.
func DurationUnitGT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldDurationUnit, v))
}

// DurationUnitGTE applies the GTE predicate on the "duration_unit" field.
func DurationUnitGTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldDurationUnit, v))
}

// DurationUnitLT applies the LT predicate on the "duration_unit" field.
func DurationUnitLT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldDurationUnit, v))
}

// DurationUnitLTE applies the LTE predicate on the "duration_unit" field.
func DurationUnitLTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldDurationUnit, v))
}

// DurationUnitContains applies the Contains predicate on the "duration_unit" field.
func DurationUnitContains(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContains(FieldDurationUnit, v))
}

// DurationUnitHasPrefix applies the HasPrefix predicate on the "duration_unit" field.
func DurationUnitHasPrefix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasPrefix(FieldDurationUnit, v))
}

// DurationUnitHasSuffix applies the HasSuffix predicate on the "duration_unit" field.
func DurationUnitHasSuffix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasSuffix(FieldDurationUnit, v))
}

// DurationUnitEqualFold applies the EqualFold predicate on the "duration_unit" field.
func DurationUnitEqualFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEqualFold(FieldDurationUnit, v))
}

// DurationUnitContainsFold applies the ContainsFold predicate on the "duration_unit" field.
func DurationUnitContainsFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContainsFold(FieldDurationUnit, v))
}

// DurationValueEQ applies the EQ predicate on the "duration_value" field.
func DurationValueEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldDurationValue, v))
}

// DurationValueNEQ applies the NEQ predicate on the "duration_value" field.
func DurationValueNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldDurationValue, v))
}

// DurationValueIn applies the In predicate on the "duration_value" field.
func DurationValueIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldDurationValue, vs...))
}

// DurationValueNotIn applies the NotIn predicate on the "duration_value" field.
func DurationValueNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldDurationValue, vs...))
}

// DurationValueGT applies the GT predicate on the "duration_value" field.
func DurationValueGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldDurationValue, v))
}

// DurationValueGTE applies the GTE predicate on the "duration_value" field.
func DurationValueGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldDurationValue, v))
}

// DurationValueLT applies the LT predicate on the "duration_value" field.
func DurationValueLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldDurationValue, v))
}

// DurationValueLTE applies the LTE predicate on the "duration_value" field.
func DurationValueLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldDurationValue, v))
}

// OptionPriceEQ applies the EQ predicate on the "option_price" field.
func OptionPriceEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldOptionPrice, v))
}

// OptionPriceNEQ applies the NEQ predicate on the "option_price" field.
func OptionPriceNEQ(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldOptionPrice, v))
}

// OptionPriceIn applies the In predicate on the "option_price" field.
func OptionPriceIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldOptionPrice, vs...))
}

// OptionPriceNotIn applies the NotIn predicate on the "option_price" field.
func OptionPriceNotIn(vs ...int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldOptionPrice, vs...))
}

// OptionPriceGT applies the GT predicate on the "option_price" field.
func OptionPriceGT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldOptionPrice, v))
}

// OptionPriceGTE applies the GTE predicate on the "option_price" field.
func OptionPriceGTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldOptionPrice, v))
}

// OptionPriceLT applies the LT predicate on the "option_price" field.
func OptionPriceLT(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldOptionPrice, v))
}

// OptionPriceLTE applies the LTE predicate on the "option_price" field.
func OptionPriceLTE(v int64) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldOptionPrice, v))
}

// SubscribeTokenEQ applies the EQ predicate on the "subscribe_token" field.
func SubscribeTokenEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldSubscribeToken, v))
}

// SubscribeTokenNEQ applies the NEQ predicate on the "subscribe_token" field.
func SubscribeTokenNEQ(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldSubscribeToken, v))
}

// SubscribeTokenIn applies the In predicate on the "subscribe_token" field.
func SubscribeTokenIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldSubscribeToken, vs...))
}

// SubscribeTokenNotIn applies the NotIn predicate on the "subscribe_token" field.
func SubscribeTokenNotIn(vs ...string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldSubscribeToken, vs...))
}

// SubscribeTokenGT applies the GT predicate on the "subscribe_token" field.
func SubscribeTokenGT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldSubscribeToken, v))
}

// SubscribeTokenGTE applies the GTE predicate on the "subscribe_token" field.
func SubscribeTokenGTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldSubscribeToken, v))
}

// SubscribeTokenLT applies the LT predicate on the "subscribe_token" field.
func SubscribeTokenLT(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldSubscribeToken, v))
}

// SubscribeTokenLTE applies the LTE predicate on the "subscribe_token" field.
func SubscribeTokenLTE(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldSubscribeToken, v))
}

// SubscribeTokenContains applies the Contains predicate on the "subscribe_token" field.
func SubscribeTokenContains(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContains(FieldSubscribeToken, v))
}

// SubscribeTokenHasPrefix applies the HasPrefix predicate on the "subscribe_token" field.
func SubscribeTokenHasPrefix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasPrefix(FieldSubscribeToken, v))
}

// SubscribeTokenHasSuffix applies the HasSuffix predicate on the "subscribe_token" field.
func SubscribeTokenHasSuffix(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldHasSuffix(FieldSubscribeToken, v))
}

// SubscribeTokenIsNil applies the IsNil predicate on the "subscribe_token" field.
func SubscribeTokenIsNil() predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIsNull(FieldSubscribeToken))
}

// SubscribeTokenNotNil applies the NotNil predicate on the "subscribe_token" field.
func SubscribeTokenNotNil() predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotNull(FieldSubscribeToken))
}

// SubscribeTokenEqualFold applies the EqualFold predicate on the "subscribe_token" field.
func SubscribeTokenEqualFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEqualFold(FieldSubscribeToken, v))
}

// SubscribeTokenContainsFold applies the ContainsFold predicate on the "subscribe_token" field.
func SubscribeTokenContainsFold(v string) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldContainsFold(FieldSubscribeToken, v))
}

// IsNewEQ applies the EQ predicate on the "is_new" field.
func IsNewEQ(v bool) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldIsNew, v))
}

// IsNewNEQ applies the NEQ predicate on the "is_new" field.
func IsNewNEQ(v bool) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldIsNew, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyOrder) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyOrder) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyOrder) predicate.ProxyOrder {
	return predicate.ProxyOrder(sql.NotPredicates(p))
}
