// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: admin/routing/v1/routing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutingService_ListRouteProfiles_FullMethodName           = "/api.admin.routing.v1.RoutingService/ListRouteProfiles"
	RoutingService_CreateRouteProfile_FullMethodName          = "/api.admin.routing.v1.RoutingService/CreateRouteProfile"
	RoutingService_UpdateRouteProfile_FullMethodName          = "/api.admin.routing.v1.RoutingService/UpdateRouteProfile"
	RoutingService_DeleteRouteProfile_FullMethodName          = "/api.admin.routing.v1.RoutingService/DeleteRouteProfile"
	RoutingService_ListRouteRules_FullMethodName              = "/api.admin.routing.v1.RoutingService/ListRouteRules"
	RoutingService_CreateRouteRule_FullMethodName             = "/api.admin.routing.v1.RoutingService/CreateRouteRule"
	RoutingService_UpdateRouteRule_FullMethodName             = "/api.admin.routing.v1.RoutingService/UpdateRouteRule"
	RoutingService_DeleteRouteRule_FullMethodName             = "/api.admin.routing.v1.RoutingService/DeleteRouteRule"
	RoutingService_ListDnsResolvers_FullMethodName            = "/api.admin.routing.v1.RoutingService/ListDnsResolvers"
	RoutingService_CreateDnsResolver_FullMethodName           = "/api.admin.routing.v1.RoutingService/CreateDnsResolver"
	RoutingService_UpdateDnsResolver_FullMethodName           = "/api.admin.routing.v1.RoutingService/UpdateDnsResolver"
	RoutingService_DeleteDnsResolver_FullMethodName           = "/api.admin.routing.v1.RoutingService/DeleteDnsResolver"
	RoutingService_ListRouteOutbounds_FullMethodName          = "/api.admin.routing.v1.RoutingService/ListRouteOutbounds"
	RoutingService_CreateRouteOutbound_FullMethodName         = "/api.admin.routing.v1.RoutingService/CreateRouteOutbound"
	RoutingService_UpdateRouteOutbound_FullMethodName         = "/api.admin.routing.v1.RoutingService/UpdateRouteOutbound"
	RoutingService_DeleteRouteOutbound_FullMethodName         = "/api.admin.routing.v1.RoutingService/DeleteRouteOutbound"
	RoutingService_ListUnlockServices_FullMethodName          = "/api.admin.routing.v1.RoutingService/ListUnlockServices"
	RoutingService_CreateUnlockService_FullMethodName         = "/api.admin.routing.v1.RoutingService/CreateUnlockService"
	RoutingService_UpdateUnlockService_FullMethodName         = "/api.admin.routing.v1.RoutingService/UpdateUnlockService"
	RoutingService_DeleteUnlockService_FullMethodName         = "/api.admin.routing.v1.RoutingService/DeleteUnlockService"
	RoutingService_PreviewRouteConfig_FullMethodName          = "/api.admin.routing.v1.RoutingService/PreviewRouteConfig"
	RoutingService_GetRoutingOverview_FullMethodName          = "/api.admin.routing.v1.RoutingService/GetRoutingOverview"
	RoutingService_ListRoutingHealthReports_FullMethodName    = "/api.admin.routing.v1.RoutingService/ListRoutingHealthReports"
	RoutingService_ListRoutingRouteEvents_FullMethodName      = "/api.admin.routing.v1.RoutingService/ListRoutingRouteEvents"
	RoutingService_GetRoutingAnalytics_FullMethodName         = "/api.admin.routing.v1.RoutingService/GetRoutingAnalytics"
	RoutingService_ListRoutingGrayReleases_FullMethodName     = "/api.admin.routing.v1.RoutingService/ListRoutingGrayReleases"
	RoutingService_CreateRoutingGrayRelease_FullMethodName    = "/api.admin.routing.v1.RoutingService/CreateRoutingGrayRelease"
	RoutingService_UpdateRoutingGrayRelease_FullMethodName    = "/api.admin.routing.v1.RoutingService/UpdateRoutingGrayRelease"
	RoutingService_DeleteRoutingGrayRelease_FullMethodName    = "/api.admin.routing.v1.RoutingService/DeleteRoutingGrayRelease"
	RoutingService_ActRoutingGrayRelease_FullMethodName       = "/api.admin.routing.v1.RoutingService/ActRoutingGrayRelease"
	RoutingService_GetRoutingReleaseGate_FullMethodName       = "/api.admin.routing.v1.RoutingService/GetRoutingReleaseGate"
	RoutingService_GetRoutingE2EChecklist_FullMethodName      = "/api.admin.routing.v1.RoutingService/GetRoutingE2EChecklist"
	RoutingService_GetRoutingCapabilityMatrix_FullMethodName  = "/api.admin.routing.v1.RoutingService/GetRoutingCapabilityMatrix"
	RoutingService_GetRoutingReleaseReport_FullMethodName     = "/api.admin.routing.v1.RoutingService/GetRoutingReleaseReport"
	RoutingService_SnapshotRoutingReleaseAudit_FullMethodName = "/api.admin.routing.v1.RoutingService/SnapshotRoutingReleaseAudit"
)

// RoutingServiceClient is the client API for RoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutingServiceClient interface {
	ListRouteProfiles(ctx context.Context, in *ListRouteProfilesRequest, opts ...grpc.CallOption) (*ListRouteProfilesReply, error)
	CreateRouteProfile(ctx context.Context, in *CreateRouteProfileRequest, opts ...grpc.CallOption) (*RouteProfileReply, error)
	UpdateRouteProfile(ctx context.Context, in *UpdateRouteProfileRequest, opts ...grpc.CallOption) (*RouteProfileReply, error)
	DeleteRouteProfile(ctx context.Context, in *DeleteRouteProfileRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error)
	ListRouteRules(ctx context.Context, in *ListRouteRulesRequest, opts ...grpc.CallOption) (*ListRouteRulesReply, error)
	CreateRouteRule(ctx context.Context, in *CreateRouteRuleRequest, opts ...grpc.CallOption) (*RouteRuleReply, error)
	UpdateRouteRule(ctx context.Context, in *UpdateRouteRuleRequest, opts ...grpc.CallOption) (*RouteRuleReply, error)
	DeleteRouteRule(ctx context.Context, in *DeleteRouteRuleRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error)
	ListDnsResolvers(ctx context.Context, in *ListDnsResolversRequest, opts ...grpc.CallOption) (*ListDnsResolversReply, error)
	CreateDnsResolver(ctx context.Context, in *CreateDnsResolverRequest, opts ...grpc.CallOption) (*DnsResolverReply, error)
	UpdateDnsResolver(ctx context.Context, in *UpdateDnsResolverRequest, opts ...grpc.CallOption) (*DnsResolverReply, error)
	DeleteDnsResolver(ctx context.Context, in *DeleteDnsResolverRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error)
	ListRouteOutbounds(ctx context.Context, in *ListRouteOutboundsRequest, opts ...grpc.CallOption) (*ListRouteOutboundsReply, error)
	CreateRouteOutbound(ctx context.Context, in *CreateRouteOutboundRequest, opts ...grpc.CallOption) (*RouteOutboundReply, error)
	UpdateRouteOutbound(ctx context.Context, in *UpdateRouteOutboundRequest, opts ...grpc.CallOption) (*RouteOutboundReply, error)
	DeleteRouteOutbound(ctx context.Context, in *DeleteRouteOutboundRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error)
	ListUnlockServices(ctx context.Context, in *ListUnlockServicesRequest, opts ...grpc.CallOption) (*ListUnlockServicesReply, error)
	CreateUnlockService(ctx context.Context, in *CreateUnlockServiceRequest, opts ...grpc.CallOption) (*UnlockServiceReply, error)
	UpdateUnlockService(ctx context.Context, in *UpdateUnlockServiceRequest, opts ...grpc.CallOption) (*UnlockServiceReply, error)
	DeleteUnlockService(ctx context.Context, in *DeleteUnlockServiceRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error)
	PreviewRouteConfig(ctx context.Context, in *PreviewRouteConfigRequest, opts ...grpc.CallOption) (*PreviewRouteConfigReply, error)
	GetRoutingOverview(ctx context.Context, in *GetRoutingOverviewRequest, opts ...grpc.CallOption) (*GetRoutingOverviewReply, error)
	ListRoutingHealthReports(ctx context.Context, in *ListRoutingHealthReportsRequest, opts ...grpc.CallOption) (*ListRoutingHealthReportsReply, error)
	ListRoutingRouteEvents(ctx context.Context, in *ListRoutingRouteEventsRequest, opts ...grpc.CallOption) (*ListRoutingRouteEventsReply, error)
	GetRoutingAnalytics(ctx context.Context, in *GetRoutingAnalyticsRequest, opts ...grpc.CallOption) (*GetRoutingAnalyticsReply, error)
	ListRoutingGrayReleases(ctx context.Context, in *ListRoutingGrayReleasesRequest, opts ...grpc.CallOption) (*ListRoutingGrayReleasesReply, error)
	CreateRoutingGrayRelease(ctx context.Context, in *CreateRoutingGrayReleaseRequest, opts ...grpc.CallOption) (*RoutingGrayReleaseReply, error)
	UpdateRoutingGrayRelease(ctx context.Context, in *UpdateRoutingGrayReleaseRequest, opts ...grpc.CallOption) (*RoutingGrayReleaseReply, error)
	DeleteRoutingGrayRelease(ctx context.Context, in *DeleteRoutingGrayReleaseRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error)
	ActRoutingGrayRelease(ctx context.Context, in *ActRoutingGrayReleaseRequest, opts ...grpc.CallOption) (*RoutingGrayReleaseReply, error)
	GetRoutingReleaseGate(ctx context.Context, in *GetRoutingReleaseGateRequest, opts ...grpc.CallOption) (*GetRoutingReleaseGateReply, error)
	GetRoutingE2EChecklist(ctx context.Context, in *GetRoutingE2EChecklistRequest, opts ...grpc.CallOption) (*GetRoutingE2EChecklistReply, error)
	GetRoutingCapabilityMatrix(ctx context.Context, in *GetRoutingCapabilityMatrixRequest, opts ...grpc.CallOption) (*GetRoutingCapabilityMatrixReply, error)
	GetRoutingReleaseReport(ctx context.Context, in *GetRoutingReleaseReportRequest, opts ...grpc.CallOption) (*GetRoutingReleaseReportReply, error)
	SnapshotRoutingReleaseAudit(ctx context.Context, in *SnapshotRoutingReleaseAuditRequest, opts ...grpc.CallOption) (*SnapshotRoutingReleaseAuditReply, error)
}

type routingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceClient(cc grpc.ClientConnInterface) RoutingServiceClient {
	return &routingServiceClient{cc}
}

func (c *routingServiceClient) ListRouteProfiles(ctx context.Context, in *ListRouteProfilesRequest, opts ...grpc.CallOption) (*ListRouteProfilesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRouteProfilesReply)
	err := c.cc.Invoke(ctx, RoutingService_ListRouteProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateRouteProfile(ctx context.Context, in *CreateRouteProfileRequest, opts ...grpc.CallOption) (*RouteProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteProfileReply)
	err := c.cc.Invoke(ctx, RoutingService_CreateRouteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateRouteProfile(ctx context.Context, in *UpdateRouteProfileRequest, opts ...grpc.CallOption) (*RouteProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteProfileReply)
	err := c.cc.Invoke(ctx, RoutingService_UpdateRouteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) DeleteRouteProfile(ctx context.Context, in *DeleteRouteProfileRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteItemReply)
	err := c.cc.Invoke(ctx, RoutingService_DeleteRouteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListRouteRules(ctx context.Context, in *ListRouteRulesRequest, opts ...grpc.CallOption) (*ListRouteRulesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRouteRulesReply)
	err := c.cc.Invoke(ctx, RoutingService_ListRouteRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateRouteRule(ctx context.Context, in *CreateRouteRuleRequest, opts ...grpc.CallOption) (*RouteRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteRuleReply)
	err := c.cc.Invoke(ctx, RoutingService_CreateRouteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateRouteRule(ctx context.Context, in *UpdateRouteRuleRequest, opts ...grpc.CallOption) (*RouteRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteRuleReply)
	err := c.cc.Invoke(ctx, RoutingService_UpdateRouteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) DeleteRouteRule(ctx context.Context, in *DeleteRouteRuleRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteItemReply)
	err := c.cc.Invoke(ctx, RoutingService_DeleteRouteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListDnsResolvers(ctx context.Context, in *ListDnsResolversRequest, opts ...grpc.CallOption) (*ListDnsResolversReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDnsResolversReply)
	err := c.cc.Invoke(ctx, RoutingService_ListDnsResolvers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateDnsResolver(ctx context.Context, in *CreateDnsResolverRequest, opts ...grpc.CallOption) (*DnsResolverReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsResolverReply)
	err := c.cc.Invoke(ctx, RoutingService_CreateDnsResolver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateDnsResolver(ctx context.Context, in *UpdateDnsResolverRequest, opts ...grpc.CallOption) (*DnsResolverReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsResolverReply)
	err := c.cc.Invoke(ctx, RoutingService_UpdateDnsResolver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) DeleteDnsResolver(ctx context.Context, in *DeleteDnsResolverRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteItemReply)
	err := c.cc.Invoke(ctx, RoutingService_DeleteDnsResolver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListRouteOutbounds(ctx context.Context, in *ListRouteOutboundsRequest, opts ...grpc.CallOption) (*ListRouteOutboundsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRouteOutboundsReply)
	err := c.cc.Invoke(ctx, RoutingService_ListRouteOutbounds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateRouteOutbound(ctx context.Context, in *CreateRouteOutboundRequest, opts ...grpc.CallOption) (*RouteOutboundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteOutboundReply)
	err := c.cc.Invoke(ctx, RoutingService_CreateRouteOutbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateRouteOutbound(ctx context.Context, in *UpdateRouteOutboundRequest, opts ...grpc.CallOption) (*RouteOutboundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteOutboundReply)
	err := c.cc.Invoke(ctx, RoutingService_UpdateRouteOutbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) DeleteRouteOutbound(ctx context.Context, in *DeleteRouteOutboundRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteItemReply)
	err := c.cc.Invoke(ctx, RoutingService_DeleteRouteOutbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListUnlockServices(ctx context.Context, in *ListUnlockServicesRequest, opts ...grpc.CallOption) (*ListUnlockServicesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUnlockServicesReply)
	err := c.cc.Invoke(ctx, RoutingService_ListUnlockServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateUnlockService(ctx context.Context, in *CreateUnlockServiceRequest, opts ...grpc.CallOption) (*UnlockServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockServiceReply)
	err := c.cc.Invoke(ctx, RoutingService_CreateUnlockService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateUnlockService(ctx context.Context, in *UpdateUnlockServiceRequest, opts ...grpc.CallOption) (*UnlockServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockServiceReply)
	err := c.cc.Invoke(ctx, RoutingService_UpdateUnlockService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) DeleteUnlockService(ctx context.Context, in *DeleteUnlockServiceRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteItemReply)
	err := c.cc.Invoke(ctx, RoutingService_DeleteUnlockService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) PreviewRouteConfig(ctx context.Context, in *PreviewRouteConfigRequest, opts ...grpc.CallOption) (*PreviewRouteConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewRouteConfigReply)
	err := c.cc.Invoke(ctx, RoutingService_PreviewRouteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetRoutingOverview(ctx context.Context, in *GetRoutingOverviewRequest, opts ...grpc.CallOption) (*GetRoutingOverviewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingOverviewReply)
	err := c.cc.Invoke(ctx, RoutingService_GetRoutingOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListRoutingHealthReports(ctx context.Context, in *ListRoutingHealthReportsRequest, opts ...grpc.CallOption) (*ListRoutingHealthReportsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutingHealthReportsReply)
	err := c.cc.Invoke(ctx, RoutingService_ListRoutingHealthReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListRoutingRouteEvents(ctx context.Context, in *ListRoutingRouteEventsRequest, opts ...grpc.CallOption) (*ListRoutingRouteEventsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutingRouteEventsReply)
	err := c.cc.Invoke(ctx, RoutingService_ListRoutingRouteEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetRoutingAnalytics(ctx context.Context, in *GetRoutingAnalyticsRequest, opts ...grpc.CallOption) (*GetRoutingAnalyticsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingAnalyticsReply)
	err := c.cc.Invoke(ctx, RoutingService_GetRoutingAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListRoutingGrayReleases(ctx context.Context, in *ListRoutingGrayReleasesRequest, opts ...grpc.CallOption) (*ListRoutingGrayReleasesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutingGrayReleasesReply)
	err := c.cc.Invoke(ctx, RoutingService_ListRoutingGrayReleases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateRoutingGrayRelease(ctx context.Context, in *CreateRoutingGrayReleaseRequest, opts ...grpc.CallOption) (*RoutingGrayReleaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutingGrayReleaseReply)
	err := c.cc.Invoke(ctx, RoutingService_CreateRoutingGrayRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateRoutingGrayRelease(ctx context.Context, in *UpdateRoutingGrayReleaseRequest, opts ...grpc.CallOption) (*RoutingGrayReleaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutingGrayReleaseReply)
	err := c.cc.Invoke(ctx, RoutingService_UpdateRoutingGrayRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) DeleteRoutingGrayRelease(ctx context.Context, in *DeleteRoutingGrayReleaseRequest, opts ...grpc.CallOption) (*DeleteRouteItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteItemReply)
	err := c.cc.Invoke(ctx, RoutingService_DeleteRoutingGrayRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ActRoutingGrayRelease(ctx context.Context, in *ActRoutingGrayReleaseRequest, opts ...grpc.CallOption) (*RoutingGrayReleaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutingGrayReleaseReply)
	err := c.cc.Invoke(ctx, RoutingService_ActRoutingGrayRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetRoutingReleaseGate(ctx context.Context, in *GetRoutingReleaseGateRequest, opts ...grpc.CallOption) (*GetRoutingReleaseGateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingReleaseGateReply)
	err := c.cc.Invoke(ctx, RoutingService_GetRoutingReleaseGate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetRoutingE2EChecklist(ctx context.Context, in *GetRoutingE2EChecklistRequest, opts ...grpc.CallOption) (*GetRoutingE2EChecklistReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingE2EChecklistReply)
	err := c.cc.Invoke(ctx, RoutingService_GetRoutingE2EChecklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetRoutingCapabilityMatrix(ctx context.Context, in *GetRoutingCapabilityMatrixRequest, opts ...grpc.CallOption) (*GetRoutingCapabilityMatrixReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingCapabilityMatrixReply)
	err := c.cc.Invoke(ctx, RoutingService_GetRoutingCapabilityMatrix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetRoutingReleaseReport(ctx context.Context, in *GetRoutingReleaseReportRequest, opts ...grpc.CallOption) (*GetRoutingReleaseReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingReleaseReportReply)
	err := c.cc.Invoke(ctx, RoutingService_GetRoutingReleaseReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) SnapshotRoutingReleaseAudit(ctx context.Context, in *SnapshotRoutingReleaseAuditRequest, opts ...grpc.CallOption) (*SnapshotRoutingReleaseAuditReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotRoutingReleaseAuditReply)
	err := c.cc.Invoke(ctx, RoutingService_SnapshotRoutingReleaseAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServiceServer is the server API for RoutingService service.
// All implementations must embed UnimplementedRoutingServiceServer
// for forward compatibility.
type RoutingServiceServer interface {
	ListRouteProfiles(context.Context, *ListRouteProfilesRequest) (*ListRouteProfilesReply, error)
	CreateRouteProfile(context.Context, *CreateRouteProfileRequest) (*RouteProfileReply, error)
	UpdateRouteProfile(context.Context, *UpdateRouteProfileRequest) (*RouteProfileReply, error)
	DeleteRouteProfile(context.Context, *DeleteRouteProfileRequest) (*DeleteRouteItemReply, error)
	ListRouteRules(context.Context, *ListRouteRulesRequest) (*ListRouteRulesReply, error)
	CreateRouteRule(context.Context, *CreateRouteRuleRequest) (*RouteRuleReply, error)
	UpdateRouteRule(context.Context, *UpdateRouteRuleRequest) (*RouteRuleReply, error)
	DeleteRouteRule(context.Context, *DeleteRouteRuleRequest) (*DeleteRouteItemReply, error)
	ListDnsResolvers(context.Context, *ListDnsResolversRequest) (*ListDnsResolversReply, error)
	CreateDnsResolver(context.Context, *CreateDnsResolverRequest) (*DnsResolverReply, error)
	UpdateDnsResolver(context.Context, *UpdateDnsResolverRequest) (*DnsResolverReply, error)
	DeleteDnsResolver(context.Context, *DeleteDnsResolverRequest) (*DeleteRouteItemReply, error)
	ListRouteOutbounds(context.Context, *ListRouteOutboundsRequest) (*ListRouteOutboundsReply, error)
	CreateRouteOutbound(context.Context, *CreateRouteOutboundRequest) (*RouteOutboundReply, error)
	UpdateRouteOutbound(context.Context, *UpdateRouteOutboundRequest) (*RouteOutboundReply, error)
	DeleteRouteOutbound(context.Context, *DeleteRouteOutboundRequest) (*DeleteRouteItemReply, error)
	ListUnlockServices(context.Context, *ListUnlockServicesRequest) (*ListUnlockServicesReply, error)
	CreateUnlockService(context.Context, *CreateUnlockServiceRequest) (*UnlockServiceReply, error)
	UpdateUnlockService(context.Context, *UpdateUnlockServiceRequest) (*UnlockServiceReply, error)
	DeleteUnlockService(context.Context, *DeleteUnlockServiceRequest) (*DeleteRouteItemReply, error)
	PreviewRouteConfig(context.Context, *PreviewRouteConfigRequest) (*PreviewRouteConfigReply, error)
	GetRoutingOverview(context.Context, *GetRoutingOverviewRequest) (*GetRoutingOverviewReply, error)
	ListRoutingHealthReports(context.Context, *ListRoutingHealthReportsRequest) (*ListRoutingHealthReportsReply, error)
	ListRoutingRouteEvents(context.Context, *ListRoutingRouteEventsRequest) (*ListRoutingRouteEventsReply, error)
	GetRoutingAnalytics(context.Context, *GetRoutingAnalyticsRequest) (*GetRoutingAnalyticsReply, error)
	ListRoutingGrayReleases(context.Context, *ListRoutingGrayReleasesRequest) (*ListRoutingGrayReleasesReply, error)
	CreateRoutingGrayRelease(context.Context, *CreateRoutingGrayReleaseRequest) (*RoutingGrayReleaseReply, error)
	UpdateRoutingGrayRelease(context.Context, *UpdateRoutingGrayReleaseRequest) (*RoutingGrayReleaseReply, error)
	DeleteRoutingGrayRelease(context.Context, *DeleteRoutingGrayReleaseRequest) (*DeleteRouteItemReply, error)
	ActRoutingGrayRelease(context.Context, *ActRoutingGrayReleaseRequest) (*RoutingGrayReleaseReply, error)
	GetRoutingReleaseGate(context.Context, *GetRoutingReleaseGateRequest) (*GetRoutingReleaseGateReply, error)
	GetRoutingE2EChecklist(context.Context, *GetRoutingE2EChecklistRequest) (*GetRoutingE2EChecklistReply, error)
	GetRoutingCapabilityMatrix(context.Context, *GetRoutingCapabilityMatrixRequest) (*GetRoutingCapabilityMatrixReply, error)
	GetRoutingReleaseReport(context.Context, *GetRoutingReleaseReportRequest) (*GetRoutingReleaseReportReply, error)
	SnapshotRoutingReleaseAudit(context.Context, *SnapshotRoutingReleaseAuditRequest) (*SnapshotRoutingReleaseAuditReply, error)
	mustEmbedUnimplementedRoutingServiceServer()
}

// UnimplementedRoutingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServiceServer struct{}

func (UnimplementedRoutingServiceServer) ListRouteProfiles(context.Context, *ListRouteProfilesRequest) (*ListRouteProfilesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRouteProfiles not implemented")
}
func (UnimplementedRoutingServiceServer) CreateRouteProfile(context.Context, *CreateRouteProfileRequest) (*RouteProfileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRouteProfile not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateRouteProfile(context.Context, *UpdateRouteProfileRequest) (*RouteProfileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRouteProfile not implemented")
}
func (UnimplementedRoutingServiceServer) DeleteRouteProfile(context.Context, *DeleteRouteProfileRequest) (*DeleteRouteItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRouteProfile not implemented")
}
func (UnimplementedRoutingServiceServer) ListRouteRules(context.Context, *ListRouteRulesRequest) (*ListRouteRulesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRouteRules not implemented")
}
func (UnimplementedRoutingServiceServer) CreateRouteRule(context.Context, *CreateRouteRuleRequest) (*RouteRuleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRouteRule not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateRouteRule(context.Context, *UpdateRouteRuleRequest) (*RouteRuleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRouteRule not implemented")
}
func (UnimplementedRoutingServiceServer) DeleteRouteRule(context.Context, *DeleteRouteRuleRequest) (*DeleteRouteItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRouteRule not implemented")
}
func (UnimplementedRoutingServiceServer) ListDnsResolvers(context.Context, *ListDnsResolversRequest) (*ListDnsResolversReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDnsResolvers not implemented")
}
func (UnimplementedRoutingServiceServer) CreateDnsResolver(context.Context, *CreateDnsResolverRequest) (*DnsResolverReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDnsResolver not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateDnsResolver(context.Context, *UpdateDnsResolverRequest) (*DnsResolverReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDnsResolver not implemented")
}
func (UnimplementedRoutingServiceServer) DeleteDnsResolver(context.Context, *DeleteDnsResolverRequest) (*DeleteRouteItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDnsResolver not implemented")
}
func (UnimplementedRoutingServiceServer) ListRouteOutbounds(context.Context, *ListRouteOutboundsRequest) (*ListRouteOutboundsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRouteOutbounds not implemented")
}
func (UnimplementedRoutingServiceServer) CreateRouteOutbound(context.Context, *CreateRouteOutboundRequest) (*RouteOutboundReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRouteOutbound not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateRouteOutbound(context.Context, *UpdateRouteOutboundRequest) (*RouteOutboundReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRouteOutbound not implemented")
}
func (UnimplementedRoutingServiceServer) DeleteRouteOutbound(context.Context, *DeleteRouteOutboundRequest) (*DeleteRouteItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRouteOutbound not implemented")
}
func (UnimplementedRoutingServiceServer) ListUnlockServices(context.Context, *ListUnlockServicesRequest) (*ListUnlockServicesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUnlockServices not implemented")
}
func (UnimplementedRoutingServiceServer) CreateUnlockService(context.Context, *CreateUnlockServiceRequest) (*UnlockServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUnlockService not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateUnlockService(context.Context, *UpdateUnlockServiceRequest) (*UnlockServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUnlockService not implemented")
}
func (UnimplementedRoutingServiceServer) DeleteUnlockService(context.Context, *DeleteUnlockServiceRequest) (*DeleteRouteItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUnlockService not implemented")
}
func (UnimplementedRoutingServiceServer) PreviewRouteConfig(context.Context, *PreviewRouteConfigRequest) (*PreviewRouteConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewRouteConfig not implemented")
}
func (UnimplementedRoutingServiceServer) GetRoutingOverview(context.Context, *GetRoutingOverviewRequest) (*GetRoutingOverviewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingOverview not implemented")
}
func (UnimplementedRoutingServiceServer) ListRoutingHealthReports(context.Context, *ListRoutingHealthReportsRequest) (*ListRoutingHealthReportsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoutingHealthReports not implemented")
}
func (UnimplementedRoutingServiceServer) ListRoutingRouteEvents(context.Context, *ListRoutingRouteEventsRequest) (*ListRoutingRouteEventsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoutingRouteEvents not implemented")
}
func (UnimplementedRoutingServiceServer) GetRoutingAnalytics(context.Context, *GetRoutingAnalyticsRequest) (*GetRoutingAnalyticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingAnalytics not implemented")
}
func (UnimplementedRoutingServiceServer) ListRoutingGrayReleases(context.Context, *ListRoutingGrayReleasesRequest) (*ListRoutingGrayReleasesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoutingGrayReleases not implemented")
}
func (UnimplementedRoutingServiceServer) CreateRoutingGrayRelease(context.Context, *CreateRoutingGrayReleaseRequest) (*RoutingGrayReleaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoutingGrayRelease not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateRoutingGrayRelease(context.Context, *UpdateRoutingGrayReleaseRequest) (*RoutingGrayReleaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoutingGrayRelease not implemented")
}
func (UnimplementedRoutingServiceServer) DeleteRoutingGrayRelease(context.Context, *DeleteRoutingGrayReleaseRequest) (*DeleteRouteItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoutingGrayRelease not implemented")
}
func (UnimplementedRoutingServiceServer) ActRoutingGrayRelease(context.Context, *ActRoutingGrayReleaseRequest) (*RoutingGrayReleaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActRoutingGrayRelease not implemented")
}
func (UnimplementedRoutingServiceServer) GetRoutingReleaseGate(context.Context, *GetRoutingReleaseGateRequest) (*GetRoutingReleaseGateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingReleaseGate not implemented")
}
func (UnimplementedRoutingServiceServer) GetRoutingE2EChecklist(context.Context, *GetRoutingE2EChecklistRequest) (*GetRoutingE2EChecklistReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingE2EChecklist not implemented")
}
func (UnimplementedRoutingServiceServer) GetRoutingCapabilityMatrix(context.Context, *GetRoutingCapabilityMatrixRequest) (*GetRoutingCapabilityMatrixReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingCapabilityMatrix not implemented")
}
func (UnimplementedRoutingServiceServer) GetRoutingReleaseReport(context.Context, *GetRoutingReleaseReportRequest) (*GetRoutingReleaseReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingReleaseReport not implemented")
}
func (UnimplementedRoutingServiceServer) SnapshotRoutingReleaseAudit(context.Context, *SnapshotRoutingReleaseAuditRequest) (*SnapshotRoutingReleaseAuditReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotRoutingReleaseAudit not implemented")
}
func (UnimplementedRoutingServiceServer) mustEmbedUnimplementedRoutingServiceServer() {}
func (UnimplementedRoutingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceServer will
// result in compilation errors.
type UnsafeRoutingServiceServer interface {
	mustEmbedUnimplementedRoutingServiceServer()
}

func RegisterRoutingServiceServer(s grpc.ServiceRegistrar, srv RoutingServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingService_ServiceDesc, srv)
}

func _RoutingService_ListRouteProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRouteProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListRouteProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListRouteProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListRouteProfiles(ctx, req.(*ListRouteProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateRouteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateRouteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateRouteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateRouteProfile(ctx, req.(*CreateRouteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateRouteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateRouteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateRouteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateRouteProfile(ctx, req.(*UpdateRouteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_DeleteRouteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).DeleteRouteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_DeleteRouteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).DeleteRouteProfile(ctx, req.(*DeleteRouteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListRouteRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRouteRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListRouteRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListRouteRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListRouteRules(ctx, req.(*ListRouteRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateRouteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateRouteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateRouteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateRouteRule(ctx, req.(*CreateRouteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateRouteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateRouteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateRouteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateRouteRule(ctx, req.(*UpdateRouteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_DeleteRouteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).DeleteRouteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_DeleteRouteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).DeleteRouteRule(ctx, req.(*DeleteRouteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListDnsResolvers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDnsResolversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListDnsResolvers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListDnsResolvers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListDnsResolvers(ctx, req.(*ListDnsResolversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateDnsResolver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDnsResolverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateDnsResolver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateDnsResolver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateDnsResolver(ctx, req.(*CreateDnsResolverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateDnsResolver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDnsResolverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateDnsResolver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateDnsResolver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateDnsResolver(ctx, req.(*UpdateDnsResolverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_DeleteDnsResolver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDnsResolverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).DeleteDnsResolver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_DeleteDnsResolver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).DeleteDnsResolver(ctx, req.(*DeleteDnsResolverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListRouteOutbounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRouteOutboundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListRouteOutbounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListRouteOutbounds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListRouteOutbounds(ctx, req.(*ListRouteOutboundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateRouteOutbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteOutboundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateRouteOutbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateRouteOutbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateRouteOutbound(ctx, req.(*CreateRouteOutboundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateRouteOutbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteOutboundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateRouteOutbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateRouteOutbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateRouteOutbound(ctx, req.(*UpdateRouteOutboundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_DeleteRouteOutbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteOutboundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).DeleteRouteOutbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_DeleteRouteOutbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).DeleteRouteOutbound(ctx, req.(*DeleteRouteOutboundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListUnlockServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUnlockServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListUnlockServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListUnlockServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListUnlockServices(ctx, req.(*ListUnlockServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateUnlockService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUnlockServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateUnlockService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateUnlockService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateUnlockService(ctx, req.(*CreateUnlockServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateUnlockService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUnlockServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateUnlockService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateUnlockService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateUnlockService(ctx, req.(*UpdateUnlockServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_DeleteUnlockService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUnlockServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).DeleteUnlockService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_DeleteUnlockService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).DeleteUnlockService(ctx, req.(*DeleteUnlockServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_PreviewRouteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewRouteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).PreviewRouteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_PreviewRouteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).PreviewRouteConfig(ctx, req.(*PreviewRouteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetRoutingOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetRoutingOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetRoutingOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetRoutingOverview(ctx, req.(*GetRoutingOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListRoutingHealthReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutingHealthReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListRoutingHealthReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListRoutingHealthReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListRoutingHealthReports(ctx, req.(*ListRoutingHealthReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListRoutingRouteEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutingRouteEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListRoutingRouteEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListRoutingRouteEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListRoutingRouteEvents(ctx, req.(*ListRoutingRouteEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetRoutingAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetRoutingAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetRoutingAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetRoutingAnalytics(ctx, req.(*GetRoutingAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListRoutingGrayReleases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutingGrayReleasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListRoutingGrayReleases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListRoutingGrayReleases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListRoutingGrayReleases(ctx, req.(*ListRoutingGrayReleasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateRoutingGrayRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoutingGrayReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateRoutingGrayRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateRoutingGrayRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateRoutingGrayRelease(ctx, req.(*CreateRoutingGrayReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateRoutingGrayRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoutingGrayReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateRoutingGrayRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateRoutingGrayRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateRoutingGrayRelease(ctx, req.(*UpdateRoutingGrayReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_DeleteRoutingGrayRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoutingGrayReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).DeleteRoutingGrayRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_DeleteRoutingGrayRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).DeleteRoutingGrayRelease(ctx, req.(*DeleteRoutingGrayReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ActRoutingGrayRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActRoutingGrayReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ActRoutingGrayRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ActRoutingGrayRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ActRoutingGrayRelease(ctx, req.(*ActRoutingGrayReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetRoutingReleaseGate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingReleaseGateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetRoutingReleaseGate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetRoutingReleaseGate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetRoutingReleaseGate(ctx, req.(*GetRoutingReleaseGateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetRoutingE2EChecklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingE2EChecklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetRoutingE2EChecklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetRoutingE2EChecklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetRoutingE2EChecklist(ctx, req.(*GetRoutingE2EChecklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetRoutingCapabilityMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingCapabilityMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetRoutingCapabilityMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetRoutingCapabilityMatrix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetRoutingCapabilityMatrix(ctx, req.(*GetRoutingCapabilityMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetRoutingReleaseReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingReleaseReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetRoutingReleaseReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetRoutingReleaseReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetRoutingReleaseReport(ctx, req.(*GetRoutingReleaseReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_SnapshotRoutingReleaseAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRoutingReleaseAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).SnapshotRoutingReleaseAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_SnapshotRoutingReleaseAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).SnapshotRoutingReleaseAudit(ctx, req.(*SnapshotRoutingReleaseAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutingService_ServiceDesc is the grpc.ServiceDesc for RoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.admin.routing.v1.RoutingService",
	HandlerType: (*RoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRouteProfiles",
			Handler:    _RoutingService_ListRouteProfiles_Handler,
		},
		{
			MethodName: "CreateRouteProfile",
			Handler:    _RoutingService_CreateRouteProfile_Handler,
		},
		{
			MethodName: "UpdateRouteProfile",
			Handler:    _RoutingService_UpdateRouteProfile_Handler,
		},
		{
			MethodName: "DeleteRouteProfile",
			Handler:    _RoutingService_DeleteRouteProfile_Handler,
		},
		{
			MethodName: "ListRouteRules",
			Handler:    _RoutingService_ListRouteRules_Handler,
		},
		{
			MethodName: "CreateRouteRule",
			Handler:    _RoutingService_CreateRouteRule_Handler,
		},
		{
			MethodName: "UpdateRouteRule",
			Handler:    _RoutingService_UpdateRouteRule_Handler,
		},
		{
			MethodName: "DeleteRouteRule",
			Handler:    _RoutingService_DeleteRouteRule_Handler,
		},
		{
			MethodName: "ListDnsResolvers",
			Handler:    _RoutingService_ListDnsResolvers_Handler,
		},
		{
			MethodName: "CreateDnsResolver",
			Handler:    _RoutingService_CreateDnsResolver_Handler,
		},
		{
			MethodName: "UpdateDnsResolver",
			Handler:    _RoutingService_UpdateDnsResolver_Handler,
		},
		{
			MethodName: "DeleteDnsResolver",
			Handler:    _RoutingService_DeleteDnsResolver_Handler,
		},
		{
			MethodName: "ListRouteOutbounds",
			Handler:    _RoutingService_ListRouteOutbounds_Handler,
		},
		{
			MethodName: "CreateRouteOutbound",
			Handler:    _RoutingService_CreateRouteOutbound_Handler,
		},
		{
			MethodName: "UpdateRouteOutbound",
			Handler:    _RoutingService_UpdateRouteOutbound_Handler,
		},
		{
			MethodName: "DeleteRouteOutbound",
			Handler:    _RoutingService_DeleteRouteOutbound_Handler,
		},
		{
			MethodName: "ListUnlockServices",
			Handler:    _RoutingService_ListUnlockServices_Handler,
		},
		{
			MethodName: "CreateUnlockService",
			Handler:    _RoutingService_CreateUnlockService_Handler,
		},
		{
			MethodName: "UpdateUnlockService",
			Handler:    _RoutingService_UpdateUnlockService_Handler,
		},
		{
			MethodName: "DeleteUnlockService",
			Handler:    _RoutingService_DeleteUnlockService_Handler,
		},
		{
			MethodName: "PreviewRouteConfig",
			Handler:    _RoutingService_PreviewRouteConfig_Handler,
		},
		{
			MethodName: "GetRoutingOverview",
			Handler:    _RoutingService_GetRoutingOverview_Handler,
		},
		{
			MethodName: "ListRoutingHealthReports",
			Handler:    _RoutingService_ListRoutingHealthReports_Handler,
		},
		{
			MethodName: "ListRoutingRouteEvents",
			Handler:    _RoutingService_ListRoutingRouteEvents_Handler,
		},
		{
			MethodName: "GetRoutingAnalytics",
			Handler:    _RoutingService_GetRoutingAnalytics_Handler,
		},
		{
			MethodName: "ListRoutingGrayReleases",
			Handler:    _RoutingService_ListRoutingGrayReleases_Handler,
		},
		{
			MethodName: "CreateRoutingGrayRelease",
			Handler:    _RoutingService_CreateRoutingGrayRelease_Handler,
		},
		{
			MethodName: "UpdateRoutingGrayRelease",
			Handler:    _RoutingService_UpdateRoutingGrayRelease_Handler,
		},
		{
			MethodName: "DeleteRoutingGrayRelease",
			Handler:    _RoutingService_DeleteRoutingGrayRelease_Handler,
		},
		{
			MethodName: "ActRoutingGrayRelease",
			Handler:    _RoutingService_ActRoutingGrayRelease_Handler,
		},
		{
			MethodName: "GetRoutingReleaseGate",
			Handler:    _RoutingService_GetRoutingReleaseGate_Handler,
		},
		{
			MethodName: "GetRoutingE2EChecklist",
			Handler:    _RoutingService_GetRoutingE2EChecklist_Handler,
		},
		{
			MethodName: "GetRoutingCapabilityMatrix",
			Handler:    _RoutingService_GetRoutingCapabilityMatrix_Handler,
		},
		{
			MethodName: "GetRoutingReleaseReport",
			Handler:    _RoutingService_GetRoutingReleaseReport_Handler,
		},
		{
			MethodName: "SnapshotRoutingReleaseAudit",
			Handler:    _RoutingService_SnapshotRoutingReleaseAudit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/routing/v1/routing.proto",
}
